// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package auth

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthResp          = user.AuthResp
	Empty             = user.Empty
	LoginReq          = user.LoginReq
	LogoutReq         = user.LogoutReq
	PasswordResetReq  = user.PasswordResetReq
	RefreshReq        = user.RefreshReq
	RegisterReq       = user.RegisterReq
	RevokeRefreshReq  = user.RevokeRefreshReq
	RevokeRefreshResp = user.RevokeRefreshResp
	SendCodeReq       = user.SendCodeReq
	SendCodeResp      = user.SendCodeResp
	VerifyTokenReq    = user.VerifyTokenReq
	VerifyTokenResp   = user.VerifyTokenResp

	Auth interface {
		SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*AuthResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*AuthResp, error)
		Refresh(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*AuthResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*Empty, error)
		VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error)
		PasswordReset(ctx context.Context, in *PasswordResetReq, opts ...grpc.CallOption) (*Empty, error)
		RevokeRefresh(ctx context.Context, in *RevokeRefreshReq, opts ...grpc.CallOption) (*RevokeRefreshResp, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

func (m *defaultAuth) SendCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*SendCodeResp, error) {
	client := user.NewAuthClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}

func (m *defaultAuth) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*AuthResp, error) {
	client := user.NewAuthClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultAuth) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*AuthResp, error) {
	client := user.NewAuthClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAuth) Refresh(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*AuthResp, error) {
	client := user.NewAuthClient(m.cli.Conn())
	return client.Refresh(ctx, in, opts...)
}

func (m *defaultAuth) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewAuthClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultAuth) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error) {
	client := user.NewAuthClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}

func (m *defaultAuth) PasswordReset(ctx context.Context, in *PasswordResetReq, opts ...grpc.CallOption) (*Empty, error) {
	client := user.NewAuthClient(m.cli.Conn())
	return client.PasswordReset(ctx, in, opts...)
}

func (m *defaultAuth) RevokeRefresh(ctx context.Context, in *RevokeRefreshReq, opts ...grpc.CallOption) (*RevokeRefreshResp, error) {
	client := user.NewAuthClient(m.cli.Conn())
	return client.RevokeRefresh(ctx, in, opts...)
}
