// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserInfo 用户基础信息（与 users 表字段对齐；avatar/bio/zg_id/... 可空时返回空串）。
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ZgId          string                 `protobuf:"bytes,6,opt,name=zg_id,json=zgId,proto3" json:"zg_id,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday      string                 `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"` // YYYY-MM-DD
	School        string                 `protobuf:"bytes,9,opt,name=school,proto3" json:"school,omitempty"`
	Bio           string                 `protobuf:"bytes,10,opt,name=bio,proto3" json:"bio,omitempty"`
	TagsJson      string                 `protobuf:"bytes,11,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,12,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"` // 仅 auth 服务内部使用
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetZgId() string {
	if x != nil {
		return x.ZgId
	}
	return ""
}

func (x *UserInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserInfo) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UserInfo) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *UserInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserInfo) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

func (x *UserInfo) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdReq) Reset() {
	*x = GetByIdReq{}
	mi := &file_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdReq) ProtoMessage() {}

func (x *GetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdReq.ProtoReflect.Descriptor instead.
func (*GetByIdReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdResp) Reset() {
	*x = GetByIdResp{}
	mi := &file_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdResp) ProtoMessage() {}

func (x *GetByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdResp.ProtoReflect.Descriptor instead.
func (*GetByIdResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetByIdResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type GetByIdentifierReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdentifierReq) Reset() {
	*x = GetByIdentifierReq{}
	mi := &file_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdentifierReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdentifierReq) ProtoMessage() {}

func (x *GetByIdentifierReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdentifierReq.ProtoReflect.Descriptor instead.
func (*GetByIdentifierReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetByIdentifierReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type GetByIdentifierResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdentifierResp) Reset() {
	*x = GetByIdentifierResp{}
	mi := &file_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdentifierResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdentifierResp) ProtoMessage() {}

func (x *GetByIdentifierResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdentifierResp.ProtoReflect.Descriptor instead.
func (*GetByIdentifierResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetByIdentifierResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type FindByIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdsReq) Reset() {
	*x = FindByIdsReq{}
	mi := &file_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdsReq) ProtoMessage() {}

func (x *FindByIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdsReq.ProtoReflect.Descriptor instead.
func (*FindByIdsReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *FindByIdsReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindByIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdsResp) Reset() {
	*x = FindByIdsResp{}
	mi := &file_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdsResp) ProtoMessage() {}

func (x *FindByIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdsResp.ProtoReflect.Descriptor instead.
func (*FindByIdsResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *FindByIdsResp) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *CreateReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateReq) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *CreateReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type CreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResp) Reset() {
	*x = CreateResp{}
	mi := &file_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResp) ProtoMessage() {}

func (x *CreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
func (*CreateResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *CreateResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ExistsByIdentifierReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByIdentifierReq) Reset() {
	*x = ExistsByIdentifierReq{}
	mi := &file_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByIdentifierReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByIdentifierReq) ProtoMessage() {}

func (x *ExistsByIdentifierReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByIdentifierReq.ProtoReflect.Descriptor instead.
func (*ExistsByIdentifierReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *ExistsByIdentifierReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type ExistsByIdentifierResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByIdentifierResp) Reset() {
	*x = ExistsByIdentifierResp{}
	mi := &file_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByIdentifierResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByIdentifierResp) ProtoMessage() {}

func (x *ExistsByIdentifierResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByIdentifierResp.ProtoReflect.Descriptor instead.
func (*ExistsByIdentifierResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *ExistsByIdentifierResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ExistsByIdentifierResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdatePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReq) Reset() {
	*x = UpdatePasswordReq{}
	mi := &file_proto_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReq) ProtoMessage() {}

func (x *UpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePasswordReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePasswordReq) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UpdatePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResp) Reset() {
	*x = UpdatePasswordResp{}
	mi := &file_proto_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResp) ProtoMessage() {}

func (x *UpdatePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResp.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePasswordResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ExistsByZgIdExceptId 用于 zg_id 唯一性校验：排除当前用户自己的记录。
type ExistsByZgIdExceptIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZgId          string                 `protobuf:"bytes,1,opt,name=zg_id,json=zgId,proto3" json:"zg_id,omitempty"`
	ExceptId      int64                  `protobuf:"varint,2,opt,name=except_id,json=exceptId,proto3" json:"except_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByZgIdExceptIdReq) Reset() {
	*x = ExistsByZgIdExceptIdReq{}
	mi := &file_proto_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByZgIdExceptIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByZgIdExceptIdReq) ProtoMessage() {}

func (x *ExistsByZgIdExceptIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByZgIdExceptIdReq.ProtoReflect.Descriptor instead.
func (*ExistsByZgIdExceptIdReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *ExistsByZgIdExceptIdReq) GetZgId() string {
	if x != nil {
		return x.ZgId
	}
	return ""
}

func (x *ExistsByZgIdExceptIdReq) GetExceptId() int64 {
	if x != nil {
		return x.ExceptId
	}
	return 0
}

type ExistsByZgIdExceptIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsByZgIdExceptIdResp) Reset() {
	*x = ExistsByZgIdExceptIdResp{}
	mi := &file_proto_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsByZgIdExceptIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsByZgIdExceptIdResp) ProtoMessage() {}

func (x *ExistsByZgIdExceptIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsByZgIdExceptIdResp.ProtoReflect.Descriptor instead.
func (*ExistsByZgIdExceptIdResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *ExistsByZgIdExceptIdResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// UpdateProfileReq 资料增量更新；用 *_set bool 区分"未传"与"显式置空串"。
type UpdateProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	NicknameSet   bool                   `protobuf:"varint,3,opt,name=nickname_set,json=nicknameSet,proto3" json:"nickname_set,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	BioSet        bool                   `protobuf:"varint,5,opt,name=bio_set,json=bioSet,proto3" json:"bio_set,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	GenderSet     bool                   `protobuf:"varint,7,opt,name=gender_set,json=genderSet,proto3" json:"gender_set,omitempty"`
	Birthday      string                 `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	BirthdaySet   bool                   `protobuf:"varint,9,opt,name=birthday_set,json=birthdaySet,proto3" json:"birthday_set,omitempty"` // YYYY-MM-DD
	ZgId          string                 `protobuf:"bytes,10,opt,name=zg_id,json=zgId,proto3" json:"zg_id,omitempty"`
	ZgIdSet       bool                   `protobuf:"varint,11,opt,name=zg_id_set,json=zgIdSet,proto3" json:"zg_id_set,omitempty"`
	School        string                 `protobuf:"bytes,12,opt,name=school,proto3" json:"school,omitempty"`
	SchoolSet     bool                   `protobuf:"varint,13,opt,name=school_set,json=schoolSet,proto3" json:"school_set,omitempty"`
	Avatar        string                 `protobuf:"bytes,14,opt,name=avatar,proto3" json:"avatar,omitempty"`
	AvatarSet     bool                   `protobuf:"varint,15,opt,name=avatar_set,json=avatarSet,proto3" json:"avatar_set,omitempty"`
	TagsJson      string                 `protobuf:"bytes,16,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"`
	TagsJsonSet   bool                   `protobuf:"varint,17,opt,name=tags_json_set,json=tagsJsonSet,proto3" json:"tags_json_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReq) Reset() {
	*x = UpdateProfileReq{}
	mi := &file_proto_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReq) ProtoMessage() {}

func (x *UpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProfileReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProfileReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileReq) GetNicknameSet() bool {
	if x != nil {
		return x.NicknameSet
	}
	return false
}

func (x *UpdateProfileReq) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileReq) GetBioSet() bool {
	if x != nil {
		return x.BioSet
	}
	return false
}

func (x *UpdateProfileReq) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateProfileReq) GetGenderSet() bool {
	if x != nil {
		return x.GenderSet
	}
	return false
}

func (x *UpdateProfileReq) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UpdateProfileReq) GetBirthdaySet() bool {
	if x != nil {
		return x.BirthdaySet
	}
	return false
}

func (x *UpdateProfileReq) GetZgId() string {
	if x != nil {
		return x.ZgId
	}
	return ""
}

func (x *UpdateProfileReq) GetZgIdSet() bool {
	if x != nil {
		return x.ZgIdSet
	}
	return false
}

func (x *UpdateProfileReq) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *UpdateProfileReq) GetSchoolSet() bool {
	if x != nil {
		return x.SchoolSet
	}
	return false
}

func (x *UpdateProfileReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfileReq) GetAvatarSet() bool {
	if x != nil {
		return x.AvatarSet
	}
	return false
}

func (x *UpdateProfileReq) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

func (x *UpdateProfileReq) GetTagsJsonSet() bool {
	if x != nil {
		return x.TagsJsonSet
	}
	return false
}

type UpdateProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResp) Reset() {
	*x = UpdateProfileResp{}
	mi := &file_proto_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResp) ProtoMessage() {}

func (x *UpdateProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateProfileResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProfileResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// TokenPair 与 Java AuthResponse / TokenResponse 字段对齐。
type TokenPair struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessExpiresAt  int64                  `protobuf:"varint,2,opt,name=access_expires_at,json=accessExpiresAt,proto3" json:"access_expires_at,omitempty"` // unix milliseconds
	RefreshToken     string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshExpiresAt int64                  `protobuf:"varint,4,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	RefreshTokenId   string                 `protobuf:"bytes,5,opt,name=refresh_token_id,json=refreshTokenId,proto3" json:"refresh_token_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_proto_user_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{17}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetAccessExpiresAt() int64 {
	if x != nil {
		return x.AccessExpiresAt
	}
	return 0
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetRefreshExpiresAt() int64 {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return 0
}

func (x *TokenPair) GetRefreshTokenId() string {
	if x != nil {
		return x.RefreshTokenId
	}
	return ""
}

type AuthUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	ZgId          string                 `protobuf:"bytes,5,opt,name=zg_id,json=zgId,proto3" json:"zg_id,omitempty"`
	Birthday      string                 `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	School        string                 `protobuf:"bytes,7,opt,name=school,proto3" json:"school,omitempty"`
	Bio           string                 `protobuf:"bytes,8,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender        string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	TagsJson      string                 `protobuf:"bytes,10,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUser) Reset() {
	*x = AuthUser{}
	mi := &file_proto_user_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUser) ProtoMessage() {}

func (x *AuthUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUser.ProtoReflect.Descriptor instead.
func (*AuthUser) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{18}
}

func (x *AuthUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AuthUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AuthUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AuthUser) GetZgId() string {
	if x != nil {
		return x.ZgId
	}
	return ""
}

func (x *AuthUser) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *AuthUser) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *AuthUser) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *AuthUser) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *AuthUser) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

type AuthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AuthUser              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         *TokenPair             `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	mi := &file_proto_user_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{19}
}

func (x *AuthResp) GetUser() *AuthUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResp) GetToken() *TokenPair {
	if x != nil {
		return x.Token
	}
	return nil
}

type SendCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scene         string                 `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`           // REGISTER / LOGIN / RESET_PASSWORD
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"` // phone / email
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeReq) Reset() {
	*x = SendCodeReq{}
	mi := &file_proto_user_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeReq) ProtoMessage() {}

func (x *SendCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeReq.ProtoReflect.Descriptor instead.
func (*SendCodeReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{20}
}

func (x *SendCodeReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *SendCodeReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type SendCodeResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CooldownSeconds int32                  `protobuf:"varint,1,opt,name=cooldown_seconds,json=cooldownSeconds,proto3" json:"cooldown_seconds,omitempty"`
	ExpireSeconds   int32                  `protobuf:"varint,2,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendCodeResp) Reset() {
	*x = SendCodeResp{}
	mi := &file_proto_user_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeResp) ProtoMessage() {}

func (x *SendCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeResp.ProtoReflect.Descriptor instead.
func (*SendCodeResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{21}
}

func (x *SendCodeResp) GetCooldownSeconds() int32 {
	if x != nil {
		return x.CooldownSeconds
	}
	return 0
}

func (x *SendCodeResp) GetExpireSeconds() int32 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AgreeTerms    bool                   `protobuf:"varint,5,opt,name=agree_terms,json=agreeTerms,proto3" json:"agree_terms,omitempty"`
	Ip            string                 `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_proto_user_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterReq) GetAgreeTerms() bool {
	if x != nil {
		return x.AgreeTerms
	}
	return false
}

func (x *RegisterReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"` // PASSWORD / CODE
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_proto_user_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{23}
}

func (x *LoginReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *LoginReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LoginReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type RefreshReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshReq) Reset() {
	*x = RefreshReq{}
	mi := &file_proto_user_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshReq) ProtoMessage() {}

func (x *RefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshReq.ProtoReflect.Descriptor instead.
func (*RefreshReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{24}
}

func (x *RefreshReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RefreshTokenId string                 `protobuf:"bytes,2,opt,name=refresh_token_id,json=refreshTokenId,proto3" json:"refresh_token_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_proto_user_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{25}
}

func (x *LogoutReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LogoutReq) GetRefreshTokenId() string {
	if x != nil {
		return x.RefreshTokenId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_user_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{26}
}

type VerifyTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenReq) Reset() {
	*x = VerifyTokenReq{}
	mi := &file_proto_user_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenReq) ProtoMessage() {}

func (x *VerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenReq.ProtoReflect.Descriptor instead.
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{27}
}

func (x *VerifyTokenReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResp) Reset() {
	*x = VerifyTokenResp{}
	mi := &file_proto_user_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResp) ProtoMessage() {}

func (x *VerifyTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResp.ProtoReflect.Descriptor instead.
func (*VerifyTokenResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{28}
}

func (x *VerifyTokenResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyTokenResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type PasswordResetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetReq) Reset() {
	*x = PasswordResetReq{}
	mi := &file_proto_user_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetReq) ProtoMessage() {}

func (x *PasswordResetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetReq.ProtoReflect.Descriptor instead.
func (*PasswordResetReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{29}
}

func (x *PasswordResetReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *PasswordResetReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PasswordResetReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type RevokeRefreshReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshReq) Reset() {
	*x = RevokeRefreshReq{}
	mi := &file_proto_user_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshReq) ProtoMessage() {}

func (x *RevokeRefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshReq.ProtoReflect.Descriptor instead.
func (*RevokeRefreshReq) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{30}
}

func (x *RevokeRefreshReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeRefreshResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRefreshResp) Reset() {
	*x = RevokeRefreshResp{}
	mi := &file_proto_user_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRefreshResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshResp) ProtoMessage() {}

func (x *RevokeRefreshResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshResp.ProtoReflect.Descriptor instead.
func (*RevokeRefreshResp) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{31}
}

func (x *RevokeRefreshResp) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

var File_proto_user_user_proto protoreflect.FileDescriptor

const file_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x15proto/user/user.proto\x12\x04user\"\xed\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x13\n" +
	"\x05zg_id\x18\x06 \x01(\tR\x04zgId\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12\x1a\n" +
	"\bbirthday\x18\b \x01(\tR\bbirthday\x12\x16\n" +
	"\x06school\x18\t \x01(\tR\x06school\x12\x10\n" +
	"\x03bio\x18\n" +
	" \x01(\tR\x03bio\x12\x1b\n" +
	"\ttags_json\x18\v \x01(\tR\btagsJson\x12#\n" +
	"\rpassword_hash\x18\f \x01(\tR\fpasswordHash\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"\x1c\n" +
	"\n" +
	"GetByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\vGetByIdResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"4\n" +
	"\x12GetByIdentifierReq\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"9\n" +
	"\x13GetByIdentifierResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\" \n" +
	"\fFindByIdsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"5\n" +
	"\rFindByIdsResp\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.user.UserInfoR\x05users\"x\n" +
	"\tCreateReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"\x1c\n" +
	"\n" +
	"CreateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\x15ExistsByIdentifierReq\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"I\n" +
	"\x16ExistsByIdentifierResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"H\n" +
	"\x11UpdatePasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"$\n" +
	"\x12UpdatePasswordResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"K\n" +
	"\x17ExistsByZgIdExceptIdReq\x12\x13\n" +
	"\x05zg_id\x18\x01 \x01(\tR\x04zgId\x12\x1b\n" +
	"\texcept_id\x18\x02 \x01(\x03R\bexceptId\"2\n" +
	"\x18ExistsByZgIdExceptIdResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\xe2\x03\n" +
	"\x10UpdateProfileReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12!\n" +
	"\fnickname_set\x18\x03 \x01(\bR\vnicknameSet\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x17\n" +
	"\abio_set\x18\x05 \x01(\bR\x06bioSet\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x1d\n" +
	"\n" +
	"gender_set\x18\a \x01(\bR\tgenderSet\x12\x1a\n" +
	"\bbirthday\x18\b \x01(\tR\bbirthday\x12!\n" +
	"\fbirthday_set\x18\t \x01(\bR\vbirthdaySet\x12\x13\n" +
	"\x05zg_id\x18\n" +
	" \x01(\tR\x04zgId\x12\x1a\n" +
	"\tzg_id_set\x18\v \x01(\bR\azgIdSet\x12\x16\n" +
	"\x06school\x18\f \x01(\tR\x06school\x12\x1d\n" +
	"\n" +
	"school_set\x18\r \x01(\bR\tschoolSet\x12\x16\n" +
	"\x06avatar\x18\x0e \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"avatar_set\x18\x0f \x01(\bR\tavatarSet\x12\x1b\n" +
	"\ttags_json\x18\x10 \x01(\tR\btagsJson\x12\"\n" +
	"\rtags_json_set\x18\x11 \x01(\bR\vtagsJsonSet\"7\n" +
	"\x11UpdateProfileResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"\xd7\x01\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12*\n" +
	"\x11access_expires_at\x18\x02 \x01(\x03R\x0faccessExpiresAt\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12,\n" +
	"\x12refresh_expires_at\x18\x04 \x01(\x03R\x10refreshExpiresAt\x12(\n" +
	"\x10refresh_token_id\x18\x05 \x01(\tR\x0erefreshTokenId\"\xf4\x01\n" +
	"\bAuthUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x13\n" +
	"\x05zg_id\x18\x05 \x01(\tR\x04zgId\x12\x1a\n" +
	"\bbirthday\x18\x06 \x01(\tR\bbirthday\x12\x16\n" +
	"\x06school\x18\a \x01(\tR\x06school\x12\x10\n" +
	"\x03bio\x18\b \x01(\tR\x03bio\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x1b\n" +
	"\ttags_json\x18\n" +
	" \x01(\tR\btagsJson\"U\n" +
	"\bAuthResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.AuthUserR\x04user\x12%\n" +
	"\x05token\x18\x02 \x01(\v2\x0f.user.TokenPairR\x05token\"C\n" +
	"\vSendCodeReq\x12\x14\n" +
	"\x05scene\x18\x01 \x01(\tR\x05scene\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\"`\n" +
	"\fSendCodeResp\x12)\n" +
	"\x10cooldown_seconds\x18\x01 \x01(\x05R\x0fcooldownSeconds\x12%\n" +
	"\x0eexpire_seconds\x18\x02 \x01(\x05R\rexpireSeconds\"\xc9\x01\n" +
	"\vRegisterReq\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x1f\n" +
	"\vagree_terms\x18\x05 \x01(\bR\n" +
	"agreeTerms\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\"\xa3\x01\n" +
	"\bLoginReq\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\"1\n" +
	"\n" +
	"RefreshReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"N\n" +
	"\tLogoutReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12(\n" +
	"\x10refresh_token_id\x18\x02 \x01(\tR\x0erefreshTokenId\"\a\n" +
	"\x05Empty\"3\n" +
	"\x0eVerifyTokenReq\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\\\n" +
	"\x0fVerifyTokenResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"i\n" +
	"\x10PasswordResetReq\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"7\n" +
	"\x10RevokeRefreshReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"-\n" +
	"\x11RevokeRefreshResp\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked2\x90\x04\n" +
	"\x04User\x12.\n" +
	"\aGetById\x12\x10.user.GetByIdReq\x1a\x11.user.GetByIdResp\x12F\n" +
	"\x0fGetByIdentifier\x12\x18.user.GetByIdentifierReq\x1a\x19.user.GetByIdentifierResp\x124\n" +
	"\tFindByIds\x12\x12.user.FindByIdsReq\x1a\x13.user.FindByIdsResp\x12+\n" +
	"\x06Create\x12\x0f.user.CreateReq\x1a\x10.user.CreateResp\x12O\n" +
	"\x12ExistsByIdentifier\x12\x1b.user.ExistsByIdentifierReq\x1a\x1c.user.ExistsByIdentifierResp\x12C\n" +
	"\x0eUpdatePassword\x12\x17.user.UpdatePasswordReq\x1a\x18.user.UpdatePasswordResp\x12U\n" +
	"\x14ExistsByZgIdExceptId\x12\x1d.user.ExistsByZgIdExceptIdReq\x1a\x1e.user.ExistsByZgIdExceptIdResp\x12@\n" +
	"\rUpdateProfile\x12\x16.user.UpdateProfileReq\x1a\x17.user.UpdateProfileResp2\x9a\x03\n" +
	"\x04Auth\x121\n" +
	"\bSendCode\x12\x11.user.SendCodeReq\x1a\x12.user.SendCodeResp\x12-\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x0e.user.AuthResp\x12'\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0e.user.AuthResp\x12+\n" +
	"\aRefresh\x12\x10.user.RefreshReq\x1a\x0e.user.AuthResp\x12&\n" +
	"\x06Logout\x12\x0f.user.LogoutReq\x1a\v.user.Empty\x12:\n" +
	"\vVerifyToken\x12\x14.user.VerifyTokenReq\x1a\x15.user.VerifyTokenResp\x124\n" +
	"\rPasswordReset\x12\x16.user.PasswordResetReq\x1a\v.user.Empty\x12@\n" +
	"\rRevokeRefresh\x12\x16.user.RevokeRefreshReq\x1a\x17.user.RevokeRefreshRespB\bZ\x06./userb\x06proto3"

var (
	file_proto_user_user_proto_rawDescOnce sync.Once
	file_proto_user_user_proto_rawDescData []byte
)

func file_proto_user_user_proto_rawDescGZIP() []byte {
	file_proto_user_user_proto_rawDescOnce.Do(func() {
		file_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)))
	})
	return file_proto_user_user_proto_rawDescData
}

var file_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_user_user_proto_goTypes = []any{
	(*UserInfo)(nil),                 // 0: user.UserInfo
	(*GetByIdReq)(nil),               // 1: user.GetByIdReq
	(*GetByIdResp)(nil),              // 2: user.GetByIdResp
	(*GetByIdentifierReq)(nil),       // 3: user.GetByIdentifierReq
	(*GetByIdentifierResp)(nil),      // 4: user.GetByIdentifierResp
	(*FindByIdsReq)(nil),             // 5: user.FindByIdsReq
	(*FindByIdsResp)(nil),            // 6: user.FindByIdsResp
	(*CreateReq)(nil),                // 7: user.CreateReq
	(*CreateResp)(nil),               // 8: user.CreateResp
	(*ExistsByIdentifierReq)(nil),    // 9: user.ExistsByIdentifierReq
	(*ExistsByIdentifierResp)(nil),   // 10: user.ExistsByIdentifierResp
	(*UpdatePasswordReq)(nil),        // 11: user.UpdatePasswordReq
	(*UpdatePasswordResp)(nil),       // 12: user.UpdatePasswordResp
	(*ExistsByZgIdExceptIdReq)(nil),  // 13: user.ExistsByZgIdExceptIdReq
	(*ExistsByZgIdExceptIdResp)(nil), // 14: user.ExistsByZgIdExceptIdResp
	(*UpdateProfileReq)(nil),         // 15: user.UpdateProfileReq
	(*UpdateProfileResp)(nil),        // 16: user.UpdateProfileResp
	(*TokenPair)(nil),                // 17: user.TokenPair
	(*AuthUser)(nil),                 // 18: user.AuthUser
	(*AuthResp)(nil),                 // 19: user.AuthResp
	(*SendCodeReq)(nil),              // 20: user.SendCodeReq
	(*SendCodeResp)(nil),             // 21: user.SendCodeResp
	(*RegisterReq)(nil),              // 22: user.RegisterReq
	(*LoginReq)(nil),                 // 23: user.LoginReq
	(*RefreshReq)(nil),               // 24: user.RefreshReq
	(*LogoutReq)(nil),                // 25: user.LogoutReq
	(*Empty)(nil),                    // 26: user.Empty
	(*VerifyTokenReq)(nil),           // 27: user.VerifyTokenReq
	(*VerifyTokenResp)(nil),          // 28: user.VerifyTokenResp
	(*PasswordResetReq)(nil),         // 29: user.PasswordResetReq
	(*RevokeRefreshReq)(nil),         // 30: user.RevokeRefreshReq
	(*RevokeRefreshResp)(nil),        // 31: user.RevokeRefreshResp
}
var file_proto_user_user_proto_depIdxs = []int32{
	0,  // 0: user.GetByIdResp.user:type_name -> user.UserInfo
	0,  // 1: user.GetByIdentifierResp.user:type_name -> user.UserInfo
	0,  // 2: user.FindByIdsResp.users:type_name -> user.UserInfo
	0,  // 3: user.UpdateProfileResp.user:type_name -> user.UserInfo
	18, // 4: user.AuthResp.user:type_name -> user.AuthUser
	17, // 5: user.AuthResp.token:type_name -> user.TokenPair
	1,  // 6: user.User.GetById:input_type -> user.GetByIdReq
	3,  // 7: user.User.GetByIdentifier:input_type -> user.GetByIdentifierReq
	5,  // 8: user.User.FindByIds:input_type -> user.FindByIdsReq
	7,  // 9: user.User.Create:input_type -> user.CreateReq
	9,  // 10: user.User.ExistsByIdentifier:input_type -> user.ExistsByIdentifierReq
	11, // 11: user.User.UpdatePassword:input_type -> user.UpdatePasswordReq
	13, // 12: user.User.ExistsByZgIdExceptId:input_type -> user.ExistsByZgIdExceptIdReq
	15, // 13: user.User.UpdateProfile:input_type -> user.UpdateProfileReq
	20, // 14: user.Auth.SendCode:input_type -> user.SendCodeReq
	22, // 15: user.Auth.Register:input_type -> user.RegisterReq
	23, // 16: user.Auth.Login:input_type -> user.LoginReq
	24, // 17: user.Auth.Refresh:input_type -> user.RefreshReq
	25, // 18: user.Auth.Logout:input_type -> user.LogoutReq
	27, // 19: user.Auth.VerifyToken:input_type -> user.VerifyTokenReq
	29, // 20: user.Auth.PasswordReset:input_type -> user.PasswordResetReq
	30, // 21: user.Auth.RevokeRefresh:input_type -> user.RevokeRefreshReq
	2,  // 22: user.User.GetById:output_type -> user.GetByIdResp
	4,  // 23: user.User.GetByIdentifier:output_type -> user.GetByIdentifierResp
	6,  // 24: user.User.FindByIds:output_type -> user.FindByIdsResp
	8,  // 25: user.User.Create:output_type -> user.CreateResp
	10, // 26: user.User.ExistsByIdentifier:output_type -> user.ExistsByIdentifierResp
	12, // 27: user.User.UpdatePassword:output_type -> user.UpdatePasswordResp
	14, // 28: user.User.ExistsByZgIdExceptId:output_type -> user.ExistsByZgIdExceptIdResp
	16, // 29: user.User.UpdateProfile:output_type -> user.UpdateProfileResp
	21, // 30: user.Auth.SendCode:output_type -> user.SendCodeResp
	19, // 31: user.Auth.Register:output_type -> user.AuthResp
	19, // 32: user.Auth.Login:output_type -> user.AuthResp
	19, // 33: user.Auth.Refresh:output_type -> user.AuthResp
	26, // 34: user.Auth.Logout:output_type -> user.Empty
	28, // 35: user.Auth.VerifyToken:output_type -> user.VerifyTokenResp
	26, // 36: user.Auth.PasswordReset:output_type -> user.Empty
	31, // 37: user.Auth.RevokeRefresh:output_type -> user.RevokeRefreshResp
	22, // [22:38] is the sub-list for method output_type
	6,  // [6:22] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_user_user_proto_init() }
func file_proto_user_user_proto_init() {
	if File_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_user_user_proto_goTypes,
		DependencyIndexes: file_proto_user_user_proto_depIdxs,
		MessageInfos:      file_proto_user_user_proto_msgTypes,
	}.Build()
	File_proto_user_user_proto = out.File
	file_proto_user_user_proto_goTypes = nil
	file_proto_user_user_proto_depIdxs = nil
}
