// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: relation.proto

package server

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/relation/rpc/internal/logic/relation"
	"github.com/zhiguang/zhiguang-go/services/relation/rpc/internal/svc"
	"github.com/zhiguang/zhiguang-go/services/relation/rpc/relation"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServer) Follow(ctx context.Context, in *relation.FollowReq) (*relation.FollowResp, error) {
	l := relationlogic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *RelationServer) Unfollow(ctx context.Context, in *relation.UnfollowReq) (*relation.UnfollowResp, error) {
	l := relationlogic.NewUnfollowLogic(ctx, s.svcCtx)
	return l.Unfollow(in)
}

func (s *RelationServer) Status(ctx context.Context, in *relation.StatusReq) (*relation.StatusResp, error) {
	l := relationlogic.NewStatusLogic(ctx, s.svcCtx)
	return l.Status(in)
}

func (s *RelationServer) ListFollowing(ctx context.Context, in *relation.ListReq) (*relation.ListResp, error) {
	l := relationlogic.NewListFollowingLogic(ctx, s.svcCtx)
	return l.ListFollowing(in)
}

func (s *RelationServer) ListFollowers(ctx context.Context, in *relation.ListReq) (*relation.ListResp, error) {
	l := relationlogic.NewListFollowersLogic(ctx, s.svcCtx)
	return l.ListFollowers(in)
}
