// Code generated by goctl. Manually adjusted: 接入 AuthRpcMiddleware（RS256 → auth-rpc.VerifyToken）。

package handler

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest"
	"github.com/zhiguang/zhiguang-go/common/middleware"
	"github.com/zhiguang/zhiguang-go/services/storage/api/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	authMw := middleware.NewAuthRpcMiddleware(serverCtx.AuthRpc, true)
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{authMw.Handle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/presign",
					Handler: PresignHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/storage"),
	)
}
