// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: counter.proto

package usercounter

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/counter/rpc/counter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetUserSnapshotReq  = counter.BatchGetUserSnapshotReq
	BatchGetUserSnapshotResp = counter.BatchGetUserSnapshotResp
	GetUserSnapshotReq       = counter.GetUserSnapshotReq
	GetUserSnapshotResp      = counter.GetUserSnapshotResp
	UserIncrementReq         = counter.UserIncrementReq
	UserIncrementResp        = counter.UserIncrementResp

	UserCounter interface {
		UserIncrement(ctx context.Context, in *UserIncrementReq, opts ...grpc.CallOption) (*UserIncrementResp, error)
		GetUserSnapshot(ctx context.Context, in *GetUserSnapshotReq, opts ...grpc.CallOption) (*GetUserSnapshotResp, error)
		BatchGetUserSnapshot(ctx context.Context, in *BatchGetUserSnapshotReq, opts ...grpc.CallOption) (*BatchGetUserSnapshotResp, error)
	}

	defaultUserCounter struct {
		cli zrpc.Client
	}
)

func NewUserCounter(cli zrpc.Client) UserCounter {
	return &defaultUserCounter{
		cli: cli,
	}
}

func (m *defaultUserCounter) UserIncrement(ctx context.Context, in *UserIncrementReq, opts ...grpc.CallOption) (*UserIncrementResp, error) {
	client := counter.NewUserCounterClient(m.cli.Conn())
	return client.UserIncrement(ctx, in, opts...)
}

func (m *defaultUserCounter) GetUserSnapshot(ctx context.Context, in *GetUserSnapshotReq, opts ...grpc.CallOption) (*GetUserSnapshotResp, error) {
	client := counter.NewUserCounterClient(m.cli.Conn())
	return client.GetUserSnapshot(ctx, in, opts...)
}

func (m *defaultUserCounter) BatchGetUserSnapshot(ctx context.Context, in *BatchGetUserSnapshotReq, opts ...grpc.CallOption) (*BatchGetUserSnapshotResp, error) {
	client := counter.NewUserCounterClient(m.cli.Conn())
	return client.BatchGetUserSnapshot(ctx, in, opts...)
}
