// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: proto/counter/counter.proto

package counter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Counter_Toggle_FullMethodName         = "/counter.Counter/Toggle"
	Counter_GetCounts_FullMethodName      = "/counter.Counter/GetCounts"
	Counter_IsMarked_FullMethodName       = "/counter.Counter/IsMarked"
	Counter_BatchGetCounts_FullMethodName = "/counter.Counter/BatchGetCounts"
)

// CounterClient is the client API for Counter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CounterClient interface {
	Toggle(ctx context.Context, in *ToggleReq, opts ...grpc.CallOption) (*ToggleResp, error)
	GetCounts(ctx context.Context, in *GetCountsReq, opts ...grpc.CallOption) (*GetCountsResp, error)
	IsMarked(ctx context.Context, in *IsMarkedReq, opts ...grpc.CallOption) (*IsMarkedResp, error)
	BatchGetCounts(ctx context.Context, in *BatchGetCountsReq, opts ...grpc.CallOption) (*BatchGetCountsResp, error)
}

type counterClient struct {
	cc grpc.ClientConnInterface
}

func NewCounterClient(cc grpc.ClientConnInterface) CounterClient {
	return &counterClient{cc}
}

func (c *counterClient) Toggle(ctx context.Context, in *ToggleReq, opts ...grpc.CallOption) (*ToggleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleResp)
	err := c.cc.Invoke(ctx, Counter_Toggle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) GetCounts(ctx context.Context, in *GetCountsReq, opts ...grpc.CallOption) (*GetCountsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCountsResp)
	err := c.cc.Invoke(ctx, Counter_GetCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) IsMarked(ctx context.Context, in *IsMarkedReq, opts ...grpc.CallOption) (*IsMarkedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsMarkedResp)
	err := c.cc.Invoke(ctx, Counter_IsMarked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterClient) BatchGetCounts(ctx context.Context, in *BatchGetCountsReq, opts ...grpc.CallOption) (*BatchGetCountsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetCountsResp)
	err := c.cc.Invoke(ctx, Counter_BatchGetCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CounterServer is the server API for Counter service.
// All implementations must embed UnimplementedCounterServer
// for forward compatibility.
type CounterServer interface {
	Toggle(context.Context, *ToggleReq) (*ToggleResp, error)
	GetCounts(context.Context, *GetCountsReq) (*GetCountsResp, error)
	IsMarked(context.Context, *IsMarkedReq) (*IsMarkedResp, error)
	BatchGetCounts(context.Context, *BatchGetCountsReq) (*BatchGetCountsResp, error)
	mustEmbedUnimplementedCounterServer()
}

// UnimplementedCounterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCounterServer struct{}

func (UnimplementedCounterServer) Toggle(context.Context, *ToggleReq) (*ToggleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Toggle not implemented")
}
func (UnimplementedCounterServer) GetCounts(context.Context, *GetCountsReq) (*GetCountsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCounts not implemented")
}
func (UnimplementedCounterServer) IsMarked(context.Context, *IsMarkedReq) (*IsMarkedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsMarked not implemented")
}
func (UnimplementedCounterServer) BatchGetCounts(context.Context, *BatchGetCountsReq) (*BatchGetCountsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetCounts not implemented")
}
func (UnimplementedCounterServer) mustEmbedUnimplementedCounterServer() {}
func (UnimplementedCounterServer) testEmbeddedByValue()                 {}

// UnsafeCounterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CounterServer will
// result in compilation errors.
type UnsafeCounterServer interface {
	mustEmbedUnimplementedCounterServer()
}

func RegisterCounterServer(s grpc.ServiceRegistrar, srv CounterServer) {
	// If the following call panics, it indicates UnimplementedCounterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Counter_ServiceDesc, srv)
}

func _Counter_Toggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).Toggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Counter_Toggle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).Toggle(ctx, req.(*ToggleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_GetCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).GetCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Counter_GetCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).GetCounts(ctx, req.(*GetCountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_IsMarked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsMarkedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).IsMarked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Counter_IsMarked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).IsMarked(ctx, req.(*IsMarkedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Counter_BatchGetCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetCountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServer).BatchGetCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Counter_BatchGetCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServer).BatchGetCounts(ctx, req.(*BatchGetCountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Counter_ServiceDesc is the grpc.ServiceDesc for Counter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Counter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "counter.Counter",
	HandlerType: (*CounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Toggle",
			Handler:    _Counter_Toggle_Handler,
		},
		{
			MethodName: "GetCounts",
			Handler:    _Counter_GetCounts_Handler,
		},
		{
			MethodName: "IsMarked",
			Handler:    _Counter_IsMarked_Handler,
		},
		{
			MethodName: "BatchGetCounts",
			Handler:    _Counter_BatchGetCounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/counter/counter.proto",
}

const (
	UserCounter_UserIncrement_FullMethodName        = "/counter.UserCounter/UserIncrement"
	UserCounter_GetUserSnapshot_FullMethodName      = "/counter.UserCounter/GetUserSnapshot"
	UserCounter_BatchGetUserSnapshot_FullMethodName = "/counter.UserCounter/BatchGetUserSnapshot"
)

// UserCounterClient is the client API for UserCounter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCounterClient interface {
	UserIncrement(ctx context.Context, in *UserIncrementReq, opts ...grpc.CallOption) (*UserIncrementResp, error)
	GetUserSnapshot(ctx context.Context, in *GetUserSnapshotReq, opts ...grpc.CallOption) (*GetUserSnapshotResp, error)
	BatchGetUserSnapshot(ctx context.Context, in *BatchGetUserSnapshotReq, opts ...grpc.CallOption) (*BatchGetUserSnapshotResp, error)
}

type userCounterClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCounterClient(cc grpc.ClientConnInterface) UserCounterClient {
	return &userCounterClient{cc}
}

func (c *userCounterClient) UserIncrement(ctx context.Context, in *UserIncrementReq, opts ...grpc.CallOption) (*UserIncrementResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserIncrementResp)
	err := c.cc.Invoke(ctx, UserCounter_UserIncrement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCounterClient) GetUserSnapshot(ctx context.Context, in *GetUserSnapshotReq, opts ...grpc.CallOption) (*GetUserSnapshotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSnapshotResp)
	err := c.cc.Invoke(ctx, UserCounter_GetUserSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCounterClient) BatchGetUserSnapshot(ctx context.Context, in *BatchGetUserSnapshotReq, opts ...grpc.CallOption) (*BatchGetUserSnapshotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetUserSnapshotResp)
	err := c.cc.Invoke(ctx, UserCounter_BatchGetUserSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCounterServer is the server API for UserCounter service.
// All implementations must embed UnimplementedUserCounterServer
// for forward compatibility.
type UserCounterServer interface {
	UserIncrement(context.Context, *UserIncrementReq) (*UserIncrementResp, error)
	GetUserSnapshot(context.Context, *GetUserSnapshotReq) (*GetUserSnapshotResp, error)
	BatchGetUserSnapshot(context.Context, *BatchGetUserSnapshotReq) (*BatchGetUserSnapshotResp, error)
	mustEmbedUnimplementedUserCounterServer()
}

// UnimplementedUserCounterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserCounterServer struct{}

func (UnimplementedUserCounterServer) UserIncrement(context.Context, *UserIncrementReq) (*UserIncrementResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserIncrement not implemented")
}
func (UnimplementedUserCounterServer) GetUserSnapshot(context.Context, *GetUserSnapshotReq) (*GetUserSnapshotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSnapshot not implemented")
}
func (UnimplementedUserCounterServer) BatchGetUserSnapshot(context.Context, *BatchGetUserSnapshotReq) (*BatchGetUserSnapshotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetUserSnapshot not implemented")
}
func (UnimplementedUserCounterServer) mustEmbedUnimplementedUserCounterServer() {}
func (UnimplementedUserCounterServer) testEmbeddedByValue()                     {}

// UnsafeUserCounterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCounterServer will
// result in compilation errors.
type UnsafeUserCounterServer interface {
	mustEmbedUnimplementedUserCounterServer()
}

func RegisterUserCounterServer(s grpc.ServiceRegistrar, srv UserCounterServer) {
	// If the following call panics, it indicates UnimplementedUserCounterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserCounter_ServiceDesc, srv)
}

func _UserCounter_UserIncrement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIncrementReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCounterServer).UserIncrement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCounter_UserIncrement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCounterServer).UserIncrement(ctx, req.(*UserIncrementReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCounter_GetUserSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSnapshotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCounterServer).GetUserSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCounter_GetUserSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCounterServer).GetUserSnapshot(ctx, req.(*GetUserSnapshotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCounter_BatchGetUserSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetUserSnapshotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCounterServer).BatchGetUserSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCounter_BatchGetUserSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCounterServer).BatchGetUserSnapshot(ctx, req.(*BatchGetUserSnapshotReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCounter_ServiceDesc is the grpc.ServiceDesc for UserCounter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCounter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "counter.UserCounter",
	HandlerType: (*UserCounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserIncrement",
			Handler:    _UserCounter_UserIncrement_Handler,
		},
		{
			MethodName: "GetUserSnapshot",
			Handler:    _UserCounter_GetUserSnapshot_Handler,
		},
		{
			MethodName: "BatchGetUserSnapshot",
			Handler:    _UserCounter_BatchGetUserSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/counter/counter.proto",
}
