// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/counter/counter.proto

package counter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToggleReq 点赞 / 收藏 切换请求。
//
//	add=true → 设置位为 1（idempotent）
//	add=false → 清除位为 0（idempotent）
type ToggleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // "knowpost"
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"` // "like" / "fav"
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Add           bool                   `protobuf:"varint,5,opt,name=add,proto3" json:"add,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleReq) Reset() {
	*x = ToggleReq{}
	mi := &file_proto_counter_counter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleReq) ProtoMessage() {}

func (x *ToggleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleReq.ProtoReflect.Descriptor instead.
func (*ToggleReq) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{0}
}

func (x *ToggleReq) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ToggleReq) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ToggleReq) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *ToggleReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ToggleReq) GetAdd() bool {
	if x != nil {
		return x.Add
	}
	return false
}

type ToggleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleResp) Reset() {
	*x = ToggleResp{}
	mi := &file_proto_counter_counter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleResp) ProtoMessage() {}

func (x *ToggleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleResp.ProtoReflect.Descriptor instead.
func (*ToggleResp) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{1}
}

func (x *ToggleResp) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type GetCountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountsReq) Reset() {
	*x = GetCountsReq{}
	mi := &file_proto_counter_counter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountsReq) ProtoMessage() {}

func (x *GetCountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountsReq.ProtoReflect.Descriptor instead.
func (*GetCountsReq) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{2}
}

func (x *GetCountsReq) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *GetCountsReq) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetCountsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        map[string]int64       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountsResp) Reset() {
	*x = GetCountsResp{}
	mi := &file_proto_counter_counter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountsResp) ProtoMessage() {}

func (x *GetCountsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountsResp.ProtoReflect.Descriptor instead.
func (*GetCountsResp) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{3}
}

func (x *GetCountsResp) GetCounts() map[string]int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type IsMarkedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"` // "like" / "fav"
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMarkedReq) Reset() {
	*x = IsMarkedReq{}
	mi := &file_proto_counter_counter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMarkedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMarkedReq) ProtoMessage() {}

func (x *IsMarkedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMarkedReq.ProtoReflect.Descriptor instead.
func (*IsMarkedReq) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{4}
}

func (x *IsMarkedReq) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *IsMarkedReq) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *IsMarkedReq) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *IsMarkedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsMarkedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Marked        bool                   `protobuf:"varint,1,opt,name=marked,proto3" json:"marked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMarkedResp) Reset() {
	*x = IsMarkedResp{}
	mi := &file_proto_counter_counter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMarkedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMarkedResp) ProtoMessage() {}

func (x *IsMarkedResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMarkedResp.ProtoReflect.Descriptor instead.
func (*IsMarkedResp) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{5}
}

func (x *IsMarkedResp) GetMarked() bool {
	if x != nil {
		return x.Marked
	}
	return false
}

type BatchGetCountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityIds     []string               `protobuf:"bytes,2,rep,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetCountsReq) Reset() {
	*x = BatchGetCountsReq{}
	mi := &file_proto_counter_counter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetCountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetCountsReq) ProtoMessage() {}

func (x *BatchGetCountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetCountsReq.ProtoReflect.Descriptor instead.
func (*BatchGetCountsReq) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetCountsReq) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *BatchGetCountsReq) GetEntityIds() []string {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

type BatchGetCountsResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Result        map[string]*GetCountsResp `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetCountsResp) Reset() {
	*x = BatchGetCountsResp{}
	mi := &file_proto_counter_counter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetCountsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetCountsResp) ProtoMessage() {}

func (x *BatchGetCountsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetCountsResp.ProtoReflect.Descriptor instead.
func (*BatchGetCountsResp) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetCountsResp) GetResult() map[string]*GetCountsResp {
	if x != nil {
		return x.Result
	}
	return nil
}

// UserSnapshot 用户维度计数全字段（与 Java UserCounterServiceImpl 严格对齐）。
type UserSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Read          int64                  `protobuf:"varint,2,opt,name=read,proto3" json:"read,omitempty"`                                        // idx 0 预留
	Followings    int64                  `protobuf:"varint,3,opt,name=followings,proto3" json:"followings,omitempty"`                            // idx 1
	Followers     int64                  `protobuf:"varint,4,opt,name=followers,proto3" json:"followers,omitempty"`                              // idx 2
	Posts         int64                  `protobuf:"varint,5,opt,name=posts,proto3" json:"posts,omitempty"`                                      // idx 3
	LikesReceived int64                  `protobuf:"varint,6,opt,name=likes_received,json=likesReceived,proto3" json:"likes_received,omitempty"` // idx 4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSnapshot) Reset() {
	*x = UserSnapshot{}
	mi := &file_proto_counter_counter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSnapshot) ProtoMessage() {}

func (x *UserSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSnapshot.ProtoReflect.Descriptor instead.
func (*UserSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{8}
}

func (x *UserSnapshot) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserSnapshot) GetRead() int64 {
	if x != nil {
		return x.Read
	}
	return 0
}

func (x *UserSnapshot) GetFollowings() int64 {
	if x != nil {
		return x.Followings
	}
	return 0
}

func (x *UserSnapshot) GetFollowers() int64 {
	if x != nil {
		return x.Followers
	}
	return 0
}

func (x *UserSnapshot) GetPosts() int64 {
	if x != nil {
		return x.Posts
	}
	return 0
}

func (x *UserSnapshot) GetLikesReceived() int64 {
	if x != nil {
		return x.LikesReceived
	}
	return 0
}

type UserIncrementReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Delta         int32                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIncrementReq) Reset() {
	*x = UserIncrementReq{}
	mi := &file_proto_counter_counter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIncrementReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIncrementReq) ProtoMessage() {}

func (x *UserIncrementReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIncrementReq.ProtoReflect.Descriptor instead.
func (*UserIncrementReq) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{9}
}

func (x *UserIncrementReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserIncrementReq) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *UserIncrementReq) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type UserIncrementResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIncrementResp) Reset() {
	*x = UserIncrementResp{}
	mi := &file_proto_counter_counter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIncrementResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIncrementResp) ProtoMessage() {}

func (x *UserIncrementResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIncrementResp.ProtoReflect.Descriptor instead.
func (*UserIncrementResp) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{10}
}

func (x *UserIncrementResp) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetUserSnapshotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSnapshotReq) Reset() {
	*x = GetUserSnapshotReq{}
	mi := &file_proto_counter_counter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSnapshotReq) ProtoMessage() {}

func (x *GetUserSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSnapshotReq.ProtoReflect.Descriptor instead.
func (*GetUserSnapshotReq) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserSnapshotReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserSnapshotResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *UserSnapshot          `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSnapshotResp) Reset() {
	*x = GetUserSnapshotResp{}
	mi := &file_proto_counter_counter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSnapshotResp) ProtoMessage() {}

func (x *GetUserSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSnapshotResp.ProtoReflect.Descriptor instead.
func (*GetUserSnapshotResp) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserSnapshotResp) GetSnapshot() *UserSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type BatchGetUserSnapshotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserSnapshotReq) Reset() {
	*x = BatchGetUserSnapshotReq{}
	mi := &file_proto_counter_counter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserSnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserSnapshotReq) ProtoMessage() {}

func (x *BatchGetUserSnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserSnapshotReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserSnapshotReq) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetUserSnapshotReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type BatchGetUserSnapshotResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Result        map[int64]*UserSnapshot `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserSnapshotResp) Reset() {
	*x = BatchGetUserSnapshotResp{}
	mi := &file_proto_counter_counter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserSnapshotResp) ProtoMessage() {}

func (x *BatchGetUserSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_counter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserSnapshotResp.ProtoReflect.Descriptor instead.
func (*BatchGetUserSnapshotResp) Descriptor() ([]byte, []int) {
	return file_proto_counter_counter_proto_rawDescGZIP(), []int{14}
}

func (x *BatchGetUserSnapshotResp) GetResult() map[int64]*UserSnapshot {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_counter_counter_proto protoreflect.FileDescriptor

const file_proto_counter_counter_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/counter/counter.proto\x12\acounter\"\x8c\x01\n" +
	"\tToggleReq\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03add\x18\x05 \x01(\bR\x03add\"&\n" +
	"\n" +
	"ToggleResp\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\"L\n" +
	"\fGetCountsReq\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\"\x86\x01\n" +
	"\rGetCountsResp\x12:\n" +
	"\x06counts\x18\x01 \x03(\v2\".counter.GetCountsResp.CountsEntryR\x06counts\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"|\n" +
	"\vIsMarkedReq\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"&\n" +
	"\fIsMarkedResp\x12\x16\n" +
	"\x06marked\x18\x01 \x01(\bR\x06marked\"S\n" +
	"\x11BatchGetCountsReq\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x02 \x03(\tR\tentityIds\"\xa8\x01\n" +
	"\x12BatchGetCountsResp\x12?\n" +
	"\x06result\x18\x01 \x03(\v2'.counter.BatchGetCountsResp.ResultEntryR\x06result\x1aQ\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.counter.GetCountsRespR\x05value:\x028\x01\"\xb6\x01\n" +
	"\fUserSnapshot\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04read\x18\x02 \x01(\x03R\x04read\x12\x1e\n" +
	"\n" +
	"followings\x18\x03 \x01(\x03R\n" +
	"followings\x12\x1c\n" +
	"\tfollowers\x18\x04 \x01(\x03R\tfollowers\x12\x14\n" +
	"\x05posts\x18\x05 \x01(\x03R\x05posts\x12%\n" +
	"\x0elikes_received\x18\x06 \x01(\x03R\rlikesReceived\"W\n" +
	"\x10UserIncrementReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x05R\x05delta\")\n" +
	"\x11UserIncrementResp\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"-\n" +
	"\x12GetUserSnapshotReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"H\n" +
	"\x13GetUserSnapshotResp\x121\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x15.counter.UserSnapshotR\bsnapshot\"4\n" +
	"\x17BatchGetUserSnapshotReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"\xb3\x01\n" +
	"\x18BatchGetUserSnapshotResp\x12E\n" +
	"\x06result\x18\x01 \x03(\v2-.counter.BatchGetUserSnapshotResp.ResultEntryR\x06result\x1aP\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.counter.UserSnapshotR\x05value:\x028\x012\xfc\x01\n" +
	"\aCounter\x121\n" +
	"\x06Toggle\x12\x12.counter.ToggleReq\x1a\x13.counter.ToggleResp\x12:\n" +
	"\tGetCounts\x12\x15.counter.GetCountsReq\x1a\x16.counter.GetCountsResp\x127\n" +
	"\bIsMarked\x12\x14.counter.IsMarkedReq\x1a\x15.counter.IsMarkedResp\x12I\n" +
	"\x0eBatchGetCounts\x12\x1a.counter.BatchGetCountsReq\x1a\x1b.counter.BatchGetCountsResp2\x80\x02\n" +
	"\vUserCounter\x12F\n" +
	"\rUserIncrement\x12\x19.counter.UserIncrementReq\x1a\x1a.counter.UserIncrementResp\x12L\n" +
	"\x0fGetUserSnapshot\x12\x1b.counter.GetUserSnapshotReq\x1a\x1c.counter.GetUserSnapshotResp\x12[\n" +
	"\x14BatchGetUserSnapshot\x12 .counter.BatchGetUserSnapshotReq\x1a!.counter.BatchGetUserSnapshotRespB\vZ\t./counterb\x06proto3"

var (
	file_proto_counter_counter_proto_rawDescOnce sync.Once
	file_proto_counter_counter_proto_rawDescData []byte
)

func file_proto_counter_counter_proto_rawDescGZIP() []byte {
	file_proto_counter_counter_proto_rawDescOnce.Do(func() {
		file_proto_counter_counter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_counter_counter_proto_rawDesc), len(file_proto_counter_counter_proto_rawDesc)))
	})
	return file_proto_counter_counter_proto_rawDescData
}

var file_proto_counter_counter_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_counter_counter_proto_goTypes = []any{
	(*ToggleReq)(nil),                // 0: counter.ToggleReq
	(*ToggleResp)(nil),               // 1: counter.ToggleResp
	(*GetCountsReq)(nil),             // 2: counter.GetCountsReq
	(*GetCountsResp)(nil),            // 3: counter.GetCountsResp
	(*IsMarkedReq)(nil),              // 4: counter.IsMarkedReq
	(*IsMarkedResp)(nil),             // 5: counter.IsMarkedResp
	(*BatchGetCountsReq)(nil),        // 6: counter.BatchGetCountsReq
	(*BatchGetCountsResp)(nil),       // 7: counter.BatchGetCountsResp
	(*UserSnapshot)(nil),             // 8: counter.UserSnapshot
	(*UserIncrementReq)(nil),         // 9: counter.UserIncrementReq
	(*UserIncrementResp)(nil),        // 10: counter.UserIncrementResp
	(*GetUserSnapshotReq)(nil),       // 11: counter.GetUserSnapshotReq
	(*GetUserSnapshotResp)(nil),      // 12: counter.GetUserSnapshotResp
	(*BatchGetUserSnapshotReq)(nil),  // 13: counter.BatchGetUserSnapshotReq
	(*BatchGetUserSnapshotResp)(nil), // 14: counter.BatchGetUserSnapshotResp
	nil,                              // 15: counter.GetCountsResp.CountsEntry
	nil,                              // 16: counter.BatchGetCountsResp.ResultEntry
	nil,                              // 17: counter.BatchGetUserSnapshotResp.ResultEntry
}
var file_proto_counter_counter_proto_depIdxs = []int32{
	15, // 0: counter.GetCountsResp.counts:type_name -> counter.GetCountsResp.CountsEntry
	16, // 1: counter.BatchGetCountsResp.result:type_name -> counter.BatchGetCountsResp.ResultEntry
	8,  // 2: counter.GetUserSnapshotResp.snapshot:type_name -> counter.UserSnapshot
	17, // 3: counter.BatchGetUserSnapshotResp.result:type_name -> counter.BatchGetUserSnapshotResp.ResultEntry
	3,  // 4: counter.BatchGetCountsResp.ResultEntry.value:type_name -> counter.GetCountsResp
	8,  // 5: counter.BatchGetUserSnapshotResp.ResultEntry.value:type_name -> counter.UserSnapshot
	0,  // 6: counter.Counter.Toggle:input_type -> counter.ToggleReq
	2,  // 7: counter.Counter.GetCounts:input_type -> counter.GetCountsReq
	4,  // 8: counter.Counter.IsMarked:input_type -> counter.IsMarkedReq
	6,  // 9: counter.Counter.BatchGetCounts:input_type -> counter.BatchGetCountsReq
	9,  // 10: counter.UserCounter.UserIncrement:input_type -> counter.UserIncrementReq
	11, // 11: counter.UserCounter.GetUserSnapshot:input_type -> counter.GetUserSnapshotReq
	13, // 12: counter.UserCounter.BatchGetUserSnapshot:input_type -> counter.BatchGetUserSnapshotReq
	1,  // 13: counter.Counter.Toggle:output_type -> counter.ToggleResp
	3,  // 14: counter.Counter.GetCounts:output_type -> counter.GetCountsResp
	5,  // 15: counter.Counter.IsMarked:output_type -> counter.IsMarkedResp
	7,  // 16: counter.Counter.BatchGetCounts:output_type -> counter.BatchGetCountsResp
	10, // 17: counter.UserCounter.UserIncrement:output_type -> counter.UserIncrementResp
	12, // 18: counter.UserCounter.GetUserSnapshot:output_type -> counter.GetUserSnapshotResp
	14, // 19: counter.UserCounter.BatchGetUserSnapshot:output_type -> counter.BatchGetUserSnapshotResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_counter_counter_proto_init() }
func file_proto_counter_counter_proto_init() {
	if File_proto_counter_counter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_counter_counter_proto_rawDesc), len(file_proto_counter_counter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_counter_counter_proto_goTypes,
		DependencyIndexes: file_proto_counter_counter_proto_depIdxs,
		MessageInfos:      file_proto_counter_counter_proto_msgTypes,
	}.Build()
	File_proto_counter_counter_proto = out.File
	file_proto_counter_counter_proto_goTypes = nil
	file_proto_counter_counter_proto_depIdxs = nil
}
