// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/knowpost/knowpost.proto

package knowpost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KnowPostDetail 帖子详情，用于详情页与发布/编辑回包。
type KnowPostDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // string 防前端精度丢失
	CreatorId        int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TagId            int64                  `protobuf:"varint,5,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Tags             []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ContentUrl       string                 `protobuf:"bytes,7,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	ContentObjectKey string                 `protobuf:"bytes,8,opt,name=content_object_key,json=contentObjectKey,proto3" json:"content_object_key,omitempty"`
	ContentEtag      string                 `protobuf:"bytes,9,opt,name=content_etag,json=contentEtag,proto3" json:"content_etag,omitempty"`
	ContentSize      int64                  `protobuf:"varint,10,opt,name=content_size,json=contentSize,proto3" json:"content_size,omitempty"`
	ContentSha256    string                 `protobuf:"bytes,11,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	ImgUrls          []string               `protobuf:"bytes,12,rep,name=img_urls,json=imgUrls,proto3" json:"img_urls,omitempty"`
	Visible          string                 `protobuf:"bytes,13,opt,name=visible,proto3" json:"visible,omitempty"` // public / followers / school / private / unlisted
	Status           string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`   // draft / published / deleted
	Type             string                 `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	IsTop            bool                   `protobuf:"varint,16,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	CreateTime       int64                  `protobuf:"varint,17,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime       int64                  `protobuf:"varint,18,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	PublishTime      int64                  `protobuf:"varint,19,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KnowPostDetail) Reset() {
	*x = KnowPostDetail{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowPostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowPostDetail) ProtoMessage() {}

func (x *KnowPostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowPostDetail.ProtoReflect.Descriptor instead.
func (*KnowPostDetail) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{0}
}

func (x *KnowPostDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowPostDetail) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *KnowPostDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowPostDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KnowPostDetail) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *KnowPostDetail) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *KnowPostDetail) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *KnowPostDetail) GetContentObjectKey() string {
	if x != nil {
		return x.ContentObjectKey
	}
	return ""
}

func (x *KnowPostDetail) GetContentEtag() string {
	if x != nil {
		return x.ContentEtag
	}
	return ""
}

func (x *KnowPostDetail) GetContentSize() int64 {
	if x != nil {
		return x.ContentSize
	}
	return 0
}

func (x *KnowPostDetail) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *KnowPostDetail) GetImgUrls() []string {
	if x != nil {
		return x.ImgUrls
	}
	return nil
}

func (x *KnowPostDetail) GetVisible() string {
	if x != nil {
		return x.Visible
	}
	return ""
}

func (x *KnowPostDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KnowPostDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KnowPostDetail) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *KnowPostDetail) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *KnowPostDetail) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *KnowPostDetail) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

// FeedItem Feed 流单条（去掉 etag/size/sha256）。
type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ContentUrl    string                 `protobuf:"bytes,5,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ImgUrls       []string               `protobuf:"bytes,7,rep,name=img_urls,json=imgUrls,proto3" json:"img_urls,omitempty"`
	Visible       string                 `protobuf:"bytes,8,opt,name=visible,proto3" json:"visible,omitempty"`
	IsTop         bool                   `protobuf:"varint,9,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	PublishTime   int64                  `protobuf:"varint,10,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{1}
}

func (x *FeedItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedItem) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *FeedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeedItem) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *FeedItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FeedItem) GetImgUrls() []string {
	if x != nil {
		return x.ImgUrls
	}
	return nil
}

func (x *FeedItem) GetVisible() string {
	if x != nil {
		return x.Visible
	}
	return ""
}

func (x *FeedItem) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *FeedItem) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

type FeedPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedPage) Reset() {
	*x = FeedPage{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedPage) ProtoMessage() {}

func (x *FeedPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedPage.ProtoReflect.Descriptor instead.
func (*FeedPage) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{2}
}

func (x *FeedPage) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FeedPage) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *FeedPage) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FeedPage) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{3}
}

type CreateDraftReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDraftReq) Reset() {
	*x = CreateDraftReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftReq) ProtoMessage() {}

func (x *CreateDraftReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftReq.ProtoReflect.Descriptor instead.
func (*CreateDraftReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDraftReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type CreateDraftResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDraftResp) Reset() {
	*x = CreateDraftResp{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftResp) ProtoMessage() {}

func (x *CreateDraftResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftResp.ProtoReflect.Descriptor instead.
func (*CreateDraftResp) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDraftResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmContentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmContentReq) Reset() {
	*x = ConfirmContentReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmContentReq) ProtoMessage() {}

func (x *ConfirmContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmContentReq.ProtoReflect.Descriptor instead.
func (*ConfirmContentReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmContentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfirmContentReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *ConfirmContentReq) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ConfirmContentReq) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ConfirmContentReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ConfirmContentReq) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// PatchMetadataReq 增量更新；用 *_set 区分未传与显式置空。
type PatchMetadataReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId      int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	TitleSet       bool                   `protobuf:"varint,4,opt,name=title_set,json=titleSet,proto3" json:"title_set,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	DescriptionSet bool                   `protobuf:"varint,6,opt,name=description_set,json=descriptionSet,proto3" json:"description_set,omitempty"`
	TagId          int64                  `protobuf:"varint,7,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	TagIdSet       bool                   `protobuf:"varint,8,opt,name=tag_id_set,json=tagIdSet,proto3" json:"tag_id_set,omitempty"`
	Tags           []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	TagsSet        bool                   `protobuf:"varint,10,opt,name=tags_set,json=tagsSet,proto3" json:"tags_set,omitempty"`
	ImgUrls        []string               `protobuf:"bytes,11,rep,name=img_urls,json=imgUrls,proto3" json:"img_urls,omitempty"`
	ImgUrlsSet     bool                   `protobuf:"varint,12,opt,name=img_urls_set,json=imgUrlsSet,proto3" json:"img_urls_set,omitempty"`
	Visible        string                 `protobuf:"bytes,13,opt,name=visible,proto3" json:"visible,omitempty"`
	VisibleSet     bool                   `protobuf:"varint,14,opt,name=visible_set,json=visibleSet,proto3" json:"visible_set,omitempty"`
	IsTop          bool                   `protobuf:"varint,15,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	IsTopSet       bool                   `protobuf:"varint,16,opt,name=is_top_set,json=isTopSet,proto3" json:"is_top_set,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PatchMetadataReq) Reset() {
	*x = PatchMetadataReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchMetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchMetadataReq) ProtoMessage() {}

func (x *PatchMetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchMetadataReq.ProtoReflect.Descriptor instead.
func (*PatchMetadataReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{7}
}

func (x *PatchMetadataReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchMetadataReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *PatchMetadataReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PatchMetadataReq) GetTitleSet() bool {
	if x != nil {
		return x.TitleSet
	}
	return false
}

func (x *PatchMetadataReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PatchMetadataReq) GetDescriptionSet() bool {
	if x != nil {
		return x.DescriptionSet
	}
	return false
}

func (x *PatchMetadataReq) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *PatchMetadataReq) GetTagIdSet() bool {
	if x != nil {
		return x.TagIdSet
	}
	return false
}

func (x *PatchMetadataReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PatchMetadataReq) GetTagsSet() bool {
	if x != nil {
		return x.TagsSet
	}
	return false
}

func (x *PatchMetadataReq) GetImgUrls() []string {
	if x != nil {
		return x.ImgUrls
	}
	return nil
}

func (x *PatchMetadataReq) GetImgUrlsSet() bool {
	if x != nil {
		return x.ImgUrlsSet
	}
	return false
}

func (x *PatchMetadataReq) GetVisible() string {
	if x != nil {
		return x.Visible
	}
	return ""
}

func (x *PatchMetadataReq) GetVisibleSet() bool {
	if x != nil {
		return x.VisibleSet
	}
	return false
}

func (x *PatchMetadataReq) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *PatchMetadataReq) GetIsTopSet() bool {
	if x != nil {
		return x.IsTopSet
	}
	return false
}

type PublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{8}
}

func (x *PublishReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type UpdateTopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	IsTop         bool                   `protobuf:"varint,3,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopReq) Reset() {
	*x = UpdateTopReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopReq) ProtoMessage() {}

func (x *UpdateTopReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopReq.ProtoReflect.Descriptor instead.
func (*UpdateTopReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTopReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTopReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *UpdateTopReq) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

type UpdateVisibilityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Visible       string                 `protobuf:"bytes,3,opt,name=visible,proto3" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVisibilityReq) Reset() {
	*x = UpdateVisibilityReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVisibilityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVisibilityReq) ProtoMessage() {}

func (x *UpdateVisibilityReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVisibilityReq.ProtoReflect.Descriptor instead.
func (*UpdateVisibilityReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVisibilityReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVisibilityReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *UpdateVisibilityReq) GetVisible() string {
	if x != nil {
		return x.Visible
	}
	return ""
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type GetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ViewerId      int64                  `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailReq) Reset() {
	*x = GetDetailReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailReq) ProtoMessage() {}

func (x *GetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailReq.ProtoReflect.Descriptor instead.
func (*GetDetailReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{12}
}

func (x *GetDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDetailReq) GetViewerId() int64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

type GetPublicFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicFeedReq) Reset() {
	*x = GetPublicFeedReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicFeedReq) ProtoMessage() {}

func (x *GetPublicFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicFeedReq.ProtoReflect.Descriptor instead.
func (*GetPublicFeedReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{13}
}

func (x *GetPublicFeedReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPublicFeedReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetMyFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyFeedReq) Reset() {
	*x = GetMyFeedReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFeedReq) ProtoMessage() {}

func (x *GetMyFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFeedReq.ProtoReflect.Descriptor instead.
func (*GetMyFeedReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{14}
}

func (x *GetMyFeedReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *GetMyFeedReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyFeedReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReindexReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexReq) Reset() {
	*x = ReindexReq{}
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexReq) ProtoMessage() {}

func (x *ReindexReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowpost_knowpost_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexReq.ProtoReflect.Descriptor instead.
func (*ReindexReq) Descriptor() ([]byte, []int) {
	return file_proto_knowpost_knowpost_proto_rawDescGZIP(), []int{15}
}

func (x *ReindexReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReindexReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

var File_proto_knowpost_knowpost_proto protoreflect.FileDescriptor

const file_proto_knowpost_knowpost_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/knowpost/knowpost.proto\x12\bknowpost\"\xbb\x04\n" +
	"\x0eKnowPostDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x15\n" +
	"\x06tag_id\x18\x05 \x01(\x03R\x05tagId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1f\n" +
	"\vcontent_url\x18\a \x01(\tR\n" +
	"contentUrl\x12,\n" +
	"\x12content_object_key\x18\b \x01(\tR\x10contentObjectKey\x12!\n" +
	"\fcontent_etag\x18\t \x01(\tR\vcontentEtag\x12!\n" +
	"\fcontent_size\x18\n" +
	" \x01(\x03R\vcontentSize\x12%\n" +
	"\x0econtent_sha256\x18\v \x01(\tR\rcontentSha256\x12\x19\n" +
	"\bimg_urls\x18\f \x03(\tR\aimgUrls\x12\x18\n" +
	"\avisible\x18\r \x01(\tR\avisible\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x0f \x01(\tR\x04type\x12\x15\n" +
	"\x06is_top\x18\x10 \x01(\bR\x05isTop\x12\x1f\n" +
	"\vcreate_time\x18\x11 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x12 \x01(\x03R\n" +
	"updateTime\x12!\n" +
	"\fpublish_time\x18\x13 \x01(\x03R\vpublishTime\"\x95\x02\n" +
	"\bFeedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcontent_url\x18\x05 \x01(\tR\n" +
	"contentUrl\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x19\n" +
	"\bimg_urls\x18\a \x03(\tR\aimgUrls\x12\x18\n" +
	"\avisible\x18\b \x01(\tR\avisible\x12\x15\n" +
	"\x06is_top\x18\t \x01(\bR\x05isTop\x12!\n" +
	"\fpublish_time\x18\n" +
	" \x01(\x03R\vpublishTime\"w\n" +
	"\bFeedPage\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.knowpost.FeedItemR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"\a\n" +
	"\x05Empty\"/\n" +
	"\x0eCreateDraftReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\"!\n" +
	"\x0fCreateDraftResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x01\n" +
	"\x11ConfirmContentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\"\xd0\x03\n" +
	"\x10PatchMetadataReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\ttitle_set\x18\x04 \x01(\bR\btitleSet\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12'\n" +
	"\x0fdescription_set\x18\x06 \x01(\bR\x0edescriptionSet\x12\x15\n" +
	"\x06tag_id\x18\a \x01(\x03R\x05tagId\x12\x1c\n" +
	"\n" +
	"tag_id_set\x18\b \x01(\bR\btagIdSet\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x19\n" +
	"\btags_set\x18\n" +
	" \x01(\bR\atagsSet\x12\x19\n" +
	"\bimg_urls\x18\v \x03(\tR\aimgUrls\x12 \n" +
	"\fimg_urls_set\x18\f \x01(\bR\n" +
	"imgUrlsSet\x12\x18\n" +
	"\avisible\x18\r \x01(\tR\avisible\x12\x1f\n" +
	"\vvisible_set\x18\x0e \x01(\bR\n" +
	"visibleSet\x12\x15\n" +
	"\x06is_top\x18\x0f \x01(\bR\x05isTop\x12\x1c\n" +
	"\n" +
	"is_top_set\x18\x10 \x01(\bR\bisTopSet\";\n" +
	"\n" +
	"PublishReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\"T\n" +
	"\fUpdateTopReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x15\n" +
	"\x06is_top\x18\x03 \x01(\bR\x05isTop\"^\n" +
	"\x13UpdateVisibilityReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x18\n" +
	"\avisible\x18\x03 \x01(\tR\avisible\":\n" +
	"\tDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\";\n" +
	"\fGetDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\x03R\bviewerId\":\n" +
	"\x10GetPublicFeedReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"U\n" +
	"\fGetMyFeedReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\";\n" +
	"\n" +
	"ReindexReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId2\xa5\x05\n" +
	"\bKnowPost\x12B\n" +
	"\vCreateDraft\x12\x18.knowpost.CreateDraftReq\x1a\x19.knowpost.CreateDraftResp\x12>\n" +
	"\x0eConfirmContent\x12\x1b.knowpost.ConfirmContentReq\x1a\x0f.knowpost.Empty\x12E\n" +
	"\rPatchMetadata\x12\x1a.knowpost.PatchMetadataReq\x1a\x18.knowpost.KnowPostDetail\x129\n" +
	"\aPublish\x12\x14.knowpost.PublishReq\x1a\x18.knowpost.KnowPostDetail\x124\n" +
	"\tUpdateTop\x12\x16.knowpost.UpdateTopReq\x1a\x0f.knowpost.Empty\x12B\n" +
	"\x10UpdateVisibility\x12\x1d.knowpost.UpdateVisibilityReq\x1a\x0f.knowpost.Empty\x12.\n" +
	"\x06Delete\x12\x13.knowpost.DeleteReq\x1a\x0f.knowpost.Empty\x12=\n" +
	"\tGetDetail\x12\x16.knowpost.GetDetailReq\x1a\x18.knowpost.KnowPostDetail\x12?\n" +
	"\rGetPublicFeed\x12\x1a.knowpost.GetPublicFeedReq\x1a\x12.knowpost.FeedPage\x127\n" +
	"\tGetMyFeed\x12\x16.knowpost.GetMyFeedReq\x1a\x12.knowpost.FeedPage\x120\n" +
	"\aReindex\x12\x14.knowpost.ReindexReq\x1a\x0f.knowpost.EmptyB\fZ\n" +
	"./knowpostb\x06proto3"

var (
	file_proto_knowpost_knowpost_proto_rawDescOnce sync.Once
	file_proto_knowpost_knowpost_proto_rawDescData []byte
)

func file_proto_knowpost_knowpost_proto_rawDescGZIP() []byte {
	file_proto_knowpost_knowpost_proto_rawDescOnce.Do(func() {
		file_proto_knowpost_knowpost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_knowpost_knowpost_proto_rawDesc), len(file_proto_knowpost_knowpost_proto_rawDesc)))
	})
	return file_proto_knowpost_knowpost_proto_rawDescData
}

var file_proto_knowpost_knowpost_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_knowpost_knowpost_proto_goTypes = []any{
	(*KnowPostDetail)(nil),      // 0: knowpost.KnowPostDetail
	(*FeedItem)(nil),            // 1: knowpost.FeedItem
	(*FeedPage)(nil),            // 2: knowpost.FeedPage
	(*Empty)(nil),               // 3: knowpost.Empty
	(*CreateDraftReq)(nil),      // 4: knowpost.CreateDraftReq
	(*CreateDraftResp)(nil),     // 5: knowpost.CreateDraftResp
	(*ConfirmContentReq)(nil),   // 6: knowpost.ConfirmContentReq
	(*PatchMetadataReq)(nil),    // 7: knowpost.PatchMetadataReq
	(*PublishReq)(nil),          // 8: knowpost.PublishReq
	(*UpdateTopReq)(nil),        // 9: knowpost.UpdateTopReq
	(*UpdateVisibilityReq)(nil), // 10: knowpost.UpdateVisibilityReq
	(*DeleteReq)(nil),           // 11: knowpost.DeleteReq
	(*GetDetailReq)(nil),        // 12: knowpost.GetDetailReq
	(*GetPublicFeedReq)(nil),    // 13: knowpost.GetPublicFeedReq
	(*GetMyFeedReq)(nil),        // 14: knowpost.GetMyFeedReq
	(*ReindexReq)(nil),          // 15: knowpost.ReindexReq
}
var file_proto_knowpost_knowpost_proto_depIdxs = []int32{
	1,  // 0: knowpost.FeedPage.items:type_name -> knowpost.FeedItem
	4,  // 1: knowpost.KnowPost.CreateDraft:input_type -> knowpost.CreateDraftReq
	6,  // 2: knowpost.KnowPost.ConfirmContent:input_type -> knowpost.ConfirmContentReq
	7,  // 3: knowpost.KnowPost.PatchMetadata:input_type -> knowpost.PatchMetadataReq
	8,  // 4: knowpost.KnowPost.Publish:input_type -> knowpost.PublishReq
	9,  // 5: knowpost.KnowPost.UpdateTop:input_type -> knowpost.UpdateTopReq
	10, // 6: knowpost.KnowPost.UpdateVisibility:input_type -> knowpost.UpdateVisibilityReq
	11, // 7: knowpost.KnowPost.Delete:input_type -> knowpost.DeleteReq
	12, // 8: knowpost.KnowPost.GetDetail:input_type -> knowpost.GetDetailReq
	13, // 9: knowpost.KnowPost.GetPublicFeed:input_type -> knowpost.GetPublicFeedReq
	14, // 10: knowpost.KnowPost.GetMyFeed:input_type -> knowpost.GetMyFeedReq
	15, // 11: knowpost.KnowPost.Reindex:input_type -> knowpost.ReindexReq
	5,  // 12: knowpost.KnowPost.CreateDraft:output_type -> knowpost.CreateDraftResp
	3,  // 13: knowpost.KnowPost.ConfirmContent:output_type -> knowpost.Empty
	0,  // 14: knowpost.KnowPost.PatchMetadata:output_type -> knowpost.KnowPostDetail
	0,  // 15: knowpost.KnowPost.Publish:output_type -> knowpost.KnowPostDetail
	3,  // 16: knowpost.KnowPost.UpdateTop:output_type -> knowpost.Empty
	3,  // 17: knowpost.KnowPost.UpdateVisibility:output_type -> knowpost.Empty
	3,  // 18: knowpost.KnowPost.Delete:output_type -> knowpost.Empty
	0,  // 19: knowpost.KnowPost.GetDetail:output_type -> knowpost.KnowPostDetail
	2,  // 20: knowpost.KnowPost.GetPublicFeed:output_type -> knowpost.FeedPage
	2,  // 21: knowpost.KnowPost.GetMyFeed:output_type -> knowpost.FeedPage
	3,  // 22: knowpost.KnowPost.Reindex:output_type -> knowpost.Empty
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_knowpost_knowpost_proto_init() }
func file_proto_knowpost_knowpost_proto_init() {
	if File_proto_knowpost_knowpost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_knowpost_knowpost_proto_rawDesc), len(file_proto_knowpost_knowpost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_knowpost_knowpost_proto_goTypes,
		DependencyIndexes: file_proto_knowpost_knowpost_proto_depIdxs,
		MessageInfos:      file_proto_knowpost_knowpost_proto_msgTypes,
	}.Build()
	File_proto_knowpost_knowpost_proto = out.File
	file_proto_knowpost_knowpost_proto_goTypes = nil
	file_proto_knowpost_knowpost_proto_depIdxs = nil
}
