// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: proto/knowpost/knowpost.proto

package knowpost

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowPost_CreateDraft_FullMethodName      = "/knowpost.KnowPost/CreateDraft"
	KnowPost_ConfirmContent_FullMethodName   = "/knowpost.KnowPost/ConfirmContent"
	KnowPost_PatchMetadata_FullMethodName    = "/knowpost.KnowPost/PatchMetadata"
	KnowPost_Publish_FullMethodName          = "/knowpost.KnowPost/Publish"
	KnowPost_UpdateTop_FullMethodName        = "/knowpost.KnowPost/UpdateTop"
	KnowPost_UpdateVisibility_FullMethodName = "/knowpost.KnowPost/UpdateVisibility"
	KnowPost_Delete_FullMethodName           = "/knowpost.KnowPost/Delete"
	KnowPost_GetDetail_FullMethodName        = "/knowpost.KnowPost/GetDetail"
	KnowPost_GetPublicFeed_FullMethodName    = "/knowpost.KnowPost/GetPublicFeed"
	KnowPost_GetMyFeed_FullMethodName        = "/knowpost.KnowPost/GetMyFeed"
	KnowPost_Reindex_FullMethodName          = "/knowpost.KnowPost/Reindex"
)

// KnowPostClient is the client API for KnowPost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowPostClient interface {
	CreateDraft(ctx context.Context, in *CreateDraftReq, opts ...grpc.CallOption) (*CreateDraftResp, error)
	ConfirmContent(ctx context.Context, in *ConfirmContentReq, opts ...grpc.CallOption) (*Empty, error)
	PatchMetadata(ctx context.Context, in *PatchMetadataReq, opts ...grpc.CallOption) (*KnowPostDetail, error)
	Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*KnowPostDetail, error)
	UpdateTop(ctx context.Context, in *UpdateTopReq, opts ...grpc.CallOption) (*Empty, error)
	UpdateVisibility(ctx context.Context, in *UpdateVisibilityReq, opts ...grpc.CallOption) (*Empty, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error)
	GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*KnowPostDetail, error)
	GetPublicFeed(ctx context.Context, in *GetPublicFeedReq, opts ...grpc.CallOption) (*FeedPage, error)
	GetMyFeed(ctx context.Context, in *GetMyFeedReq, opts ...grpc.CallOption) (*FeedPage, error)
	Reindex(ctx context.Context, in *ReindexReq, opts ...grpc.CallOption) (*Empty, error)
}

type knowPostClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowPostClient(cc grpc.ClientConnInterface) KnowPostClient {
	return &knowPostClient{cc}
}

func (c *knowPostClient) CreateDraft(ctx context.Context, in *CreateDraftReq, opts ...grpc.CallOption) (*CreateDraftResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDraftResp)
	err := c.cc.Invoke(ctx, KnowPost_CreateDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) ConfirmContent(ctx context.Context, in *ConfirmContentReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, KnowPost_ConfirmContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) PatchMetadata(ctx context.Context, in *PatchMetadataReq, opts ...grpc.CallOption) (*KnowPostDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowPostDetail)
	err := c.cc.Invoke(ctx, KnowPost_PatchMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*KnowPostDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowPostDetail)
	err := c.cc.Invoke(ctx, KnowPost_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) UpdateTop(ctx context.Context, in *UpdateTopReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, KnowPost_UpdateTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) UpdateVisibility(ctx context.Context, in *UpdateVisibilityReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, KnowPost_UpdateVisibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, KnowPost_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*KnowPostDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowPostDetail)
	err := c.cc.Invoke(ctx, KnowPost_GetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) GetPublicFeed(ctx context.Context, in *GetPublicFeedReq, opts ...grpc.CallOption) (*FeedPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedPage)
	err := c.cc.Invoke(ctx, KnowPost_GetPublicFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) GetMyFeed(ctx context.Context, in *GetMyFeedReq, opts ...grpc.CallOption) (*FeedPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedPage)
	err := c.cc.Invoke(ctx, KnowPost_GetMyFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowPostClient) Reindex(ctx context.Context, in *ReindexReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, KnowPost_Reindex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowPostServer is the server API for KnowPost service.
// All implementations must embed UnimplementedKnowPostServer
// for forward compatibility.
type KnowPostServer interface {
	CreateDraft(context.Context, *CreateDraftReq) (*CreateDraftResp, error)
	ConfirmContent(context.Context, *ConfirmContentReq) (*Empty, error)
	PatchMetadata(context.Context, *PatchMetadataReq) (*KnowPostDetail, error)
	Publish(context.Context, *PublishReq) (*KnowPostDetail, error)
	UpdateTop(context.Context, *UpdateTopReq) (*Empty, error)
	UpdateVisibility(context.Context, *UpdateVisibilityReq) (*Empty, error)
	Delete(context.Context, *DeleteReq) (*Empty, error)
	GetDetail(context.Context, *GetDetailReq) (*KnowPostDetail, error)
	GetPublicFeed(context.Context, *GetPublicFeedReq) (*FeedPage, error)
	GetMyFeed(context.Context, *GetMyFeedReq) (*FeedPage, error)
	Reindex(context.Context, *ReindexReq) (*Empty, error)
	mustEmbedUnimplementedKnowPostServer()
}

// UnimplementedKnowPostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowPostServer struct{}

func (UnimplementedKnowPostServer) CreateDraft(context.Context, *CreateDraftReq) (*CreateDraftResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDraft not implemented")
}
func (UnimplementedKnowPostServer) ConfirmContent(context.Context, *ConfirmContentReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmContent not implemented")
}
func (UnimplementedKnowPostServer) PatchMetadata(context.Context, *PatchMetadataReq) (*KnowPostDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchMetadata not implemented")
}
func (UnimplementedKnowPostServer) Publish(context.Context, *PublishReq) (*KnowPostDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedKnowPostServer) UpdateTop(context.Context, *UpdateTopReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTop not implemented")
}
func (UnimplementedKnowPostServer) UpdateVisibility(context.Context, *UpdateVisibilityReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVisibility not implemented")
}
func (UnimplementedKnowPostServer) Delete(context.Context, *DeleteReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKnowPostServer) GetDetail(context.Context, *GetDetailReq) (*KnowPostDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedKnowPostServer) GetPublicFeed(context.Context, *GetPublicFeedReq) (*FeedPage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicFeed not implemented")
}
func (UnimplementedKnowPostServer) GetMyFeed(context.Context, *GetMyFeedReq) (*FeedPage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyFeed not implemented")
}
func (UnimplementedKnowPostServer) Reindex(context.Context, *ReindexReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Reindex not implemented")
}
func (UnimplementedKnowPostServer) mustEmbedUnimplementedKnowPostServer() {}
func (UnimplementedKnowPostServer) testEmbeddedByValue()                  {}

// UnsafeKnowPostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowPostServer will
// result in compilation errors.
type UnsafeKnowPostServer interface {
	mustEmbedUnimplementedKnowPostServer()
}

func RegisterKnowPostServer(s grpc.ServiceRegistrar, srv KnowPostServer) {
	// If the following call panics, it indicates UnimplementedKnowPostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowPost_ServiceDesc, srv)
}

func _KnowPost_CreateDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDraftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).CreateDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_CreateDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).CreateDraft(ctx, req.(*CreateDraftReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_ConfirmContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).ConfirmContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_ConfirmContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).ConfirmContent(ctx, req.(*ConfirmContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_PatchMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchMetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).PatchMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_PatchMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).PatchMetadata(ctx, req.(*PatchMetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).Publish(ctx, req.(*PublishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_UpdateTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).UpdateTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_UpdateTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).UpdateTop(ctx, req.(*UpdateTopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_UpdateVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVisibilityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).UpdateVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_UpdateVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).UpdateVisibility(ctx, req.(*UpdateVisibilityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).GetDetail(ctx, req.(*GetDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_GetPublicFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).GetPublicFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_GetPublicFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).GetPublicFeed(ctx, req.(*GetPublicFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_GetMyFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).GetMyFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_GetMyFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).GetMyFeed(ctx, req.(*GetMyFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowPost_Reindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowPostServer).Reindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowPost_Reindex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowPostServer).Reindex(ctx, req.(*ReindexReq))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowPost_ServiceDesc is the grpc.ServiceDesc for KnowPost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowPost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowpost.KnowPost",
	HandlerType: (*KnowPostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDraft",
			Handler:    _KnowPost_CreateDraft_Handler,
		},
		{
			MethodName: "ConfirmContent",
			Handler:    _KnowPost_ConfirmContent_Handler,
		},
		{
			MethodName: "PatchMetadata",
			Handler:    _KnowPost_PatchMetadata_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _KnowPost_Publish_Handler,
		},
		{
			MethodName: "UpdateTop",
			Handler:    _KnowPost_UpdateTop_Handler,
		},
		{
			MethodName: "UpdateVisibility",
			Handler:    _KnowPost_UpdateVisibility_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KnowPost_Delete_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _KnowPost_GetDetail_Handler,
		},
		{
			MethodName: "GetPublicFeed",
			Handler:    _KnowPost_GetPublicFeed_Handler,
		},
		{
			MethodName: "GetMyFeed",
			Handler:    _KnowPost_GetMyFeed_Handler,
		},
		{
			MethodName: "Reindex",
			Handler:    _KnowPost_Reindex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/knowpost/knowpost.proto",
}
