// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: knowpost.proto

package knowpost

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/knowpost/rpc/knowpost"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConfirmContentReq   = knowpost.ConfirmContentReq
	CreateDraftReq      = knowpost.CreateDraftReq
	CreateDraftResp     = knowpost.CreateDraftResp
	DeleteReq           = knowpost.DeleteReq
	Empty               = knowpost.Empty
	FeedPage            = knowpost.FeedPage
	GetDetailReq        = knowpost.GetDetailReq
	GetMyFeedReq        = knowpost.GetMyFeedReq
	GetPublicFeedReq    = knowpost.GetPublicFeedReq
	KnowPostDetail      = knowpost.KnowPostDetail
	PatchMetadataReq    = knowpost.PatchMetadataReq
	PublishReq          = knowpost.PublishReq
	ReindexReq          = knowpost.ReindexReq
	UpdateTopReq        = knowpost.UpdateTopReq
	UpdateVisibilityReq = knowpost.UpdateVisibilityReq

	KnowPost interface {
		CreateDraft(ctx context.Context, in *CreateDraftReq, opts ...grpc.CallOption) (*CreateDraftResp, error)
		ConfirmContent(ctx context.Context, in *ConfirmContentReq, opts ...grpc.CallOption) (*Empty, error)
		PatchMetadata(ctx context.Context, in *PatchMetadataReq, opts ...grpc.CallOption) (*KnowPostDetail, error)
		Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*KnowPostDetail, error)
		UpdateTop(ctx context.Context, in *UpdateTopReq, opts ...grpc.CallOption) (*Empty, error)
		UpdateVisibility(ctx context.Context, in *UpdateVisibilityReq, opts ...grpc.CallOption) (*Empty, error)
		Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error)
		GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*KnowPostDetail, error)
		GetPublicFeed(ctx context.Context, in *GetPublicFeedReq, opts ...grpc.CallOption) (*FeedPage, error)
		GetMyFeed(ctx context.Context, in *GetMyFeedReq, opts ...grpc.CallOption) (*FeedPage, error)
		Reindex(ctx context.Context, in *ReindexReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultKnowPost struct {
		cli zrpc.Client
	}
)

func NewKnowPost(cli zrpc.Client) KnowPost {
	return &defaultKnowPost{
		cli: cli,
	}
}

func (m *defaultKnowPost) CreateDraft(ctx context.Context, in *CreateDraftReq, opts ...grpc.CallOption) (*CreateDraftResp, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.CreateDraft(ctx, in, opts...)
}

func (m *defaultKnowPost) ConfirmContent(ctx context.Context, in *ConfirmContentReq, opts ...grpc.CallOption) (*Empty, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.ConfirmContent(ctx, in, opts...)
}

func (m *defaultKnowPost) PatchMetadata(ctx context.Context, in *PatchMetadataReq, opts ...grpc.CallOption) (*KnowPostDetail, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.PatchMetadata(ctx, in, opts...)
}

func (m *defaultKnowPost) Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*KnowPostDetail, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

func (m *defaultKnowPost) UpdateTop(ctx context.Context, in *UpdateTopReq, opts ...grpc.CallOption) (*Empty, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.UpdateTop(ctx, in, opts...)
}

func (m *defaultKnowPost) UpdateVisibility(ctx context.Context, in *UpdateVisibilityReq, opts ...grpc.CallOption) (*Empty, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.UpdateVisibility(ctx, in, opts...)
}

func (m *defaultKnowPost) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}

func (m *defaultKnowPost) GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*KnowPostDetail, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.GetDetail(ctx, in, opts...)
}

func (m *defaultKnowPost) GetPublicFeed(ctx context.Context, in *GetPublicFeedReq, opts ...grpc.CallOption) (*FeedPage, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.GetPublicFeed(ctx, in, opts...)
}

func (m *defaultKnowPost) GetMyFeed(ctx context.Context, in *GetMyFeedReq, opts ...grpc.CallOption) (*FeedPage, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.GetMyFeed(ctx, in, opts...)
}

func (m *defaultKnowPost) Reindex(ctx context.Context, in *ReindexReq, opts ...grpc.CallOption) (*Empty, error) {
	client := knowpost.NewKnowPostClient(m.cli.Conn())
	return client.Reindex(ctx, in, opts...)
}
