// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: counter.proto

package server

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/counter/rpc/counter"
	"github.com/zhiguang/zhiguang-go/services/counter/rpc/internal/logic/counter"
	"github.com/zhiguang/zhiguang-go/services/counter/rpc/internal/svc"
)

type CounterServer struct {
	svcCtx *svc.ServiceContext
	counter.UnimplementedCounterServer
}

func NewCounterServer(svcCtx *svc.ServiceContext) *CounterServer {
	return &CounterServer{
		svcCtx: svcCtx,
	}
}

func (s *CounterServer) Toggle(ctx context.Context, in *counter.ToggleReq) (*counter.ToggleResp, error) {
	l := counterlogic.NewToggleLogic(ctx, s.svcCtx)
	return l.Toggle(in)
}

func (s *CounterServer) GetCounts(ctx context.Context, in *counter.GetCountsReq) (*counter.GetCountsResp, error) {
	l := counterlogic.NewGetCountsLogic(ctx, s.svcCtx)
	return l.GetCounts(in)
}

func (s *CounterServer) IsMarked(ctx context.Context, in *counter.IsMarkedReq) (*counter.IsMarkedResp, error) {
	l := counterlogic.NewIsMarkedLogic(ctx, s.svcCtx)
	return l.IsMarked(in)
}

func (s *CounterServer) BatchGetCounts(ctx context.Context, in *counter.BatchGetCountsReq) (*counter.BatchGetCountsResp, error) {
	l := counterlogic.NewBatchGetCountsLogic(ctx, s.svcCtx)
	return l.BatchGetCounts(in)
}
