// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type PatchProfileReq struct {
	Nickname *string `json:"nickname,optional"`
	Bio      *string `json:"bio,optional"`
	Gender   *string `json:"gender,optional"`
	Birthday *string `json:"birthday,optional"`
	ZgId     *string `json:"zgId,optional"`
	School   *string `json:"school,optional"`
	TagsJson *string `json:"tagsJson,optional"`
	TagJson  *string `json:"tagJson,optional"`
	Phone    *string `json:"phone,optional"`
	Email    *string `json:"email,optional"`
}

type ProfileResp struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
	ZgId     string `json:"zgId"`
	Gender   string `json:"gender"`
	Birthday string `json:"birthday"`
	School   string `json:"school"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	TagsJson string `json:"tagsJson"`
	TagJson  string `json:"tagJson"`
}

type UploadAvatarResp struct {
	Url       string `json:"url"`
	Avatar    string `json:"avatar"`
	ObjectKey string `json:"objectKey"`
}
