// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/user/rpc/internal/logic/user"
	"github.com/zhiguang/zhiguang-go/services/user/rpc/internal/svc"
	"github.com/zhiguang/zhiguang-go/services/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetById(ctx context.Context, in *user.GetByIdReq) (*user.GetByIdResp, error) {
	l := userlogic.NewGetByIdLogic(ctx, s.svcCtx)
	return l.GetById(in)
}

func (s *UserServer) GetByIdentifier(ctx context.Context, in *user.GetByIdentifierReq) (*user.GetByIdentifierResp, error) {
	l := userlogic.NewGetByIdentifierLogic(ctx, s.svcCtx)
	return l.GetByIdentifier(in)
}

func (s *UserServer) FindByIds(ctx context.Context, in *user.FindByIdsReq) (*user.FindByIdsResp, error) {
	l := userlogic.NewFindByIdsLogic(ctx, s.svcCtx)
	return l.FindByIds(in)
}

func (s *UserServer) Create(ctx context.Context, in *user.CreateReq) (*user.CreateResp, error) {
	l := userlogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *UserServer) ExistsByIdentifier(ctx context.Context, in *user.ExistsByIdentifierReq) (*user.ExistsByIdentifierResp, error) {
	l := userlogic.NewExistsByIdentifierLogic(ctx, s.svcCtx)
	return l.ExistsByIdentifier(in)
}

func (s *UserServer) UpdatePassword(ctx context.Context, in *user.UpdatePasswordReq) (*user.UpdatePasswordResp, error) {
	l := userlogic.NewUpdatePasswordLogic(ctx, s.svcCtx)
	return l.UpdatePassword(in)
}

func (s *UserServer) ExistsByZgIdExceptId(ctx context.Context, in *user.ExistsByZgIdExceptIdReq) (*user.ExistsByZgIdExceptIdResp, error) {
	l := userlogic.NewExistsByZgIdExceptIdLogic(ctx, s.svcCtx)
	return l.ExistsByZgIdExceptId(in)
}

func (s *UserServer) UpdateProfile(ctx context.Context, in *user.UpdateProfileReq) (*user.UpdateProfileResp, error) {
	l := userlogic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}
