// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package user

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReq                = user.CreateReq
	CreateResp               = user.CreateResp
	ExistsByIdentifierReq    = user.ExistsByIdentifierReq
	ExistsByIdentifierResp   = user.ExistsByIdentifierResp
	ExistsByZgIdExceptIdReq  = user.ExistsByZgIdExceptIdReq
	ExistsByZgIdExceptIdResp = user.ExistsByZgIdExceptIdResp
	FindByIdsReq             = user.FindByIdsReq
	FindByIdsResp            = user.FindByIdsResp
	GetByIdReq               = user.GetByIdReq
	GetByIdResp              = user.GetByIdResp
	GetByIdentifierReq       = user.GetByIdentifierReq
	GetByIdentifierResp      = user.GetByIdentifierResp
	UpdatePasswordReq        = user.UpdatePasswordReq
	UpdatePasswordResp       = user.UpdatePasswordResp
	UpdateProfileReq         = user.UpdateProfileReq
	UpdateProfileResp        = user.UpdateProfileResp

	User interface {
		GetById(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetByIdResp, error)
		GetByIdentifier(ctx context.Context, in *GetByIdentifierReq, opts ...grpc.CallOption) (*GetByIdentifierResp, error)
		FindByIds(ctx context.Context, in *FindByIdsReq, opts ...grpc.CallOption) (*FindByIdsResp, error)
		Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
		ExistsByIdentifier(ctx context.Context, in *ExistsByIdentifierReq, opts ...grpc.CallOption) (*ExistsByIdentifierResp, error)
		UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error)
		ExistsByZgIdExceptId(ctx context.Context, in *ExistsByZgIdExceptIdReq, opts ...grpc.CallOption) (*ExistsByZgIdExceptIdResp, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UpdateProfileResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetById(ctx context.Context, in *GetByIdReq, opts ...grpc.CallOption) (*GetByIdResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetById(ctx, in, opts...)
}

func (m *defaultUser) GetByIdentifier(ctx context.Context, in *GetByIdentifierReq, opts ...grpc.CallOption) (*GetByIdentifierResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetByIdentifier(ctx, in, opts...)
}

func (m *defaultUser) FindByIds(ctx context.Context, in *FindByIdsReq, opts ...grpc.CallOption) (*FindByIdsResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FindByIds(ctx, in, opts...)
}

func (m *defaultUser) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultUser) ExistsByIdentifier(ctx context.Context, in *ExistsByIdentifierReq, opts ...grpc.CallOption) (*ExistsByIdentifierResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ExistsByIdentifier(ctx, in, opts...)
}

func (m *defaultUser) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in, opts...)
}

func (m *defaultUser) ExistsByZgIdExceptId(ctx context.Context, in *ExistsByZgIdExceptIdReq, opts ...grpc.CallOption) (*ExistsByZgIdExceptIdResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ExistsByZgIdExceptId(ctx, in, opts...)
}

func (m *defaultUser) UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UpdateProfileResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}
