// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Empty struct {
}

type FollowReq struct {
	ToUserId int64 `json:"toUserId,optional" form:"toUserId,optional"`
}

type ListReq struct {
	UserId int64 `form:"userId,optional"` // 0 表示当前登录用户
	Limit  int32 `form:"limit,optional"`
	Offset int32 `form:"offset,optional"`
	Cursor int64 `form:"cursor,optional"`
}

type StatusReq struct {
	ToUserId int64 `form:"toUserId"`
}

type StatusResp struct {
	Following  bool `json:"following"`
	FollowedBy bool `json:"followedBy"`
	Mutual     bool `json:"mutual"`
}

type UnfollowReq struct {
	ToUserId int64 `json:"toUserId,optional" form:"toUserId,optional"`
}

type CounterReq struct {
	UserId int64 `form:"userId,optional"` // 0 表示当前登录用户
}

type CounterResp struct {
	Followings int64 `json:"followings"`
	Followers  int64 `json:"followers"`
	Posts      int64 `json:"posts"`
	LikedPosts int64 `json:"likedPosts"`
	FavedPosts int64 `json:"favedPosts"`
}

type UserSummary struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
	ZgId     string `json:"zgId"`
	Gender   string `json:"gender,optional"`
	Birthday string `json:"birthday,optional"`
	School   string `json:"school,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	TagJson  string `json:"tagJson,optional"`
}
