// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followingFieldNames          = builder.RawFieldNames(&Following{})
	followingRows                = strings.Join(followingFieldNames, ",")
	followingRowsExpectAutoSet   = strings.Join(stringx.Remove(followingFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followingRowsWithPlaceHolder = strings.Join(stringx.Remove(followingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFollowingIdPrefix                 = "cache:following:id:"
	cacheFollowingFromUserIdToUserIdPrefix = "cache:following:fromUserId:toUserId:"
)

type (
	followingModel interface {
		Insert(ctx context.Context, data *Following) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Following, error)
		FindOneByFromUserIdToUserId(ctx context.Context, fromUserId uint64, toUserId uint64) (*Following, error)
		Update(ctx context.Context, data *Following) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFollowingModel struct {
		sqlc.CachedConn
		table string
	}

	Following struct {
		Id         uint64    `db:"id"`
		FromUserId uint64    `db:"from_user_id"`
		ToUserId   uint64    `db:"to_user_id"`
		RelStatus  int64     `db:"rel_status"`
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
	}
)

func newFollowingModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFollowingModel {
	return &defaultFollowingModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`following`",
	}
}

func (m *defaultFollowingModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	followingFromUserIdToUserIdKey := fmt.Sprintf("%s%v:%v", cacheFollowingFromUserIdToUserIdPrefix, data.FromUserId, data.ToUserId)
	followingIdKey := fmt.Sprintf("%s%v", cacheFollowingIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, followingFromUserIdToUserIdKey, followingIdKey)
	return err
}

func (m *defaultFollowingModel) FindOne(ctx context.Context, id uint64) (*Following, error) {
	followingIdKey := fmt.Sprintf("%s%v", cacheFollowingIdPrefix, id)
	var resp Following
	err := m.QueryRowCtx(ctx, &resp, followingIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followingRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowingModel) FindOneByFromUserIdToUserId(ctx context.Context, fromUserId uint64, toUserId uint64) (*Following, error) {
	followingFromUserIdToUserIdKey := fmt.Sprintf("%s%v:%v", cacheFollowingFromUserIdToUserIdPrefix, fromUserId, toUserId)
	var resp Following
	err := m.QueryRowIndexCtx(ctx, &resp, followingFromUserIdToUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `from_user_id` = ? and `to_user_id` = ? limit 1", followingRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, fromUserId, toUserId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowingModel) Insert(ctx context.Context, data *Following) (sql.Result, error) {
	followingFromUserIdToUserIdKey := fmt.Sprintf("%s%v:%v", cacheFollowingFromUserIdToUserIdPrefix, data.FromUserId, data.ToUserId)
	followingIdKey := fmt.Sprintf("%s%v", cacheFollowingIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, followingRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.FromUserId, data.ToUserId, data.RelStatus)
	}, followingFromUserIdToUserIdKey, followingIdKey)
	return ret, err
}

func (m *defaultFollowingModel) Update(ctx context.Context, newData *Following) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	followingFromUserIdToUserIdKey := fmt.Sprintf("%s%v:%v", cacheFollowingFromUserIdToUserIdPrefix, data.FromUserId, data.ToUserId)
	followingIdKey := fmt.Sprintf("%s%v", cacheFollowingIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followingRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.FromUserId, newData.ToUserId, newData.RelStatus, newData.Id)
	}, followingFromUserIdToUserIdKey, followingIdKey)
	return err
}

func (m *defaultFollowingModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFollowingIdPrefix, primary)
}

func (m *defaultFollowingModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followingRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFollowingModel) tableName() string {
	return m.table
}
