// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followerFieldNames          = builder.RawFieldNames(&Follower{})
	followerRows                = strings.Join(followerFieldNames, ",")
	followerRowsExpectAutoSet   = strings.Join(stringx.Remove(followerFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followerRowsWithPlaceHolder = strings.Join(stringx.Remove(followerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFollowerIdPrefix                 = "cache:follower:id:"
	cacheFollowerToUserIdFromUserIdPrefix = "cache:follower:toUserId:fromUserId:"
)

type (
	followerModel interface {
		Insert(ctx context.Context, data *Follower) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Follower, error)
		FindOneByToUserIdFromUserId(ctx context.Context, toUserId uint64, fromUserId uint64) (*Follower, error)
		Update(ctx context.Context, data *Follower) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFollowerModel struct {
		sqlc.CachedConn
		table string
	}

	Follower struct {
		Id         uint64    `db:"id"`
		ToUserId   uint64    `db:"to_user_id"`
		FromUserId uint64    `db:"from_user_id"`
		RelStatus  int64     `db:"rel_status"`
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
	}
)

func newFollowerModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFollowerModel {
	return &defaultFollowerModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`follower`",
	}
}

func (m *defaultFollowerModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	followerIdKey := fmt.Sprintf("%s%v", cacheFollowerIdPrefix, id)
	followerToUserIdFromUserIdKey := fmt.Sprintf("%s%v:%v", cacheFollowerToUserIdFromUserIdPrefix, data.ToUserId, data.FromUserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, followerIdKey, followerToUserIdFromUserIdKey)
	return err
}

func (m *defaultFollowerModel) FindOne(ctx context.Context, id uint64) (*Follower, error) {
	followerIdKey := fmt.Sprintf("%s%v", cacheFollowerIdPrefix, id)
	var resp Follower
	err := m.QueryRowCtx(ctx, &resp, followerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowerModel) FindOneByToUserIdFromUserId(ctx context.Context, toUserId uint64, fromUserId uint64) (*Follower, error) {
	followerToUserIdFromUserIdKey := fmt.Sprintf("%s%v:%v", cacheFollowerToUserIdFromUserIdPrefix, toUserId, fromUserId)
	var resp Follower
	err := m.QueryRowIndexCtx(ctx, &resp, followerToUserIdFromUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `to_user_id` = ? and `from_user_id` = ? limit 1", followerRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, toUserId, fromUserId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowerModel) Insert(ctx context.Context, data *Follower) (sql.Result, error) {
	followerIdKey := fmt.Sprintf("%s%v", cacheFollowerIdPrefix, data.Id)
	followerToUserIdFromUserIdKey := fmt.Sprintf("%s%v:%v", cacheFollowerToUserIdFromUserIdPrefix, data.ToUserId, data.FromUserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, followerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.ToUserId, data.FromUserId, data.RelStatus)
	}, followerIdKey, followerToUserIdFromUserIdKey)
	return ret, err
}

func (m *defaultFollowerModel) Update(ctx context.Context, newData *Follower) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	followerIdKey := fmt.Sprintf("%s%v", cacheFollowerIdPrefix, data.Id)
	followerToUserIdFromUserIdKey := fmt.Sprintf("%s%v:%v", cacheFollowerToUserIdFromUserIdPrefix, data.ToUserId, data.FromUserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ToUserId, newData.FromUserId, newData.RelStatus, newData.Id)
	}, followerIdKey, followerToUserIdFromUserIdKey)
	return err
}

func (m *defaultFollowerModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFollowerIdPrefix, primary)
}

func (m *defaultFollowerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFollowerModel) tableName() string {
	return m.table
}
