// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ConfirmContentReq struct {
	ObjectKey string `json:"objectKey"`
	Etag      string `json:"etag,optional"`
	Size      int64  `json:"size,optional"`
	Sha256    string `json:"sha256,optional"`
}

type CreateDraftResp struct {
	Id string `json:"id"`
}

type Empty struct {
}

type FeedItem struct {
	Id             string   `json:"id"`
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	CoverImage     string   `json:"coverImage"`
	Tags           []string `json:"tags"`
	TagJson        string   `json:"tagJson"`
	AuthorAvatar   string   `json:"authorAvatar"`
	AuthorNickname string   `json:"authorNickname"`
	LikeCount      int64    `json:"likeCount"`
	FavoriteCount  int64    `json:"favoriteCount"`
	Liked          bool     `json:"liked"`
	Faved          bool     `json:"faved"`
	IsTop          bool     `json:"isTop"`
	Visible        string   `json:"visible"`
	PublishTime    int64    `json:"publishTime"`
}

type FeedPage struct {
	Items   []FeedItem `json:"items"`
	HasMore bool       `json:"hasMore"`
	Size    int32      `json:"size"`
	Page    int32      `json:"page"`
}

type GetMyFeedReq struct {
	Page int32 `form:"page,optional"`
	Size int32 `form:"size,optional"`
}

type GetPublicFeedReq struct {
	Page int32 `form:"page,optional"`
	Size int32 `form:"size,optional"`
}

type IdPath struct {
	Id int64 `path:"id"`
}

type KnowPostDetail struct {
	Id             string   `json:"id"`
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	ContentUrl     string   `json:"contentUrl"`
	Images         []string `json:"images"`
	Tags           []string `json:"tags"`
	AuthorId       int64    `json:"authorId"`
	AuthorAvatar   string   `json:"authorAvatar"`
	AuthorNickname string   `json:"authorNickname"`
	AuthorTagJson  string   `json:"authorTagJson"`
	LikeCount      int64    `json:"likeCount"`
	FavoriteCount  int64    `json:"favoriteCount"`
	Liked          bool     `json:"liked"`
	Faved          bool     `json:"faved"`
	IsTop          bool     `json:"isTop"`
	Visible        string   `json:"visible"`
	Type           string   `json:"type"`
	PublishTime    int64    `json:"publishTime"`
}

type PatchMetadataReq struct {
	Title       *string  `json:"title,optional"`
	Description *string  `json:"description,optional"`
	TagId       *int64   `json:"tagId,optional"`
	Tags        []string `json:"tags,optional"`
	TagsSet     bool     `json:"tagsSet,optional"`
	ImgUrls     []string `json:"imgUrls,optional"`
	ImgUrlsSet  bool     `json:"imgUrlsSet,optional"`
	Visible     *string  `json:"visible,optional"`
	IsTop       *bool    `json:"isTop,optional"`
}

type UpdateTopReq struct {
	IsTop bool `json:"isTop"`
}

type UpdateVisibilityReq struct {
	Visible string `json:"visible"`
}
