// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: relation.proto

package relation

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/relation/rpc/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FollowReq    = relation.FollowReq
	FollowResp   = relation.FollowResp
	ListReq      = relation.ListReq
	ListResp     = relation.ListResp
	StatusReq    = relation.StatusReq
	StatusResp   = relation.StatusResp
	UnfollowReq  = relation.UnfollowReq
	UnfollowResp = relation.UnfollowResp

	Relation interface {
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
		Status(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusResp, error)
		ListFollowing(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
		ListFollowers(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
	}

	defaultRelation struct {
		cli zrpc.Client
	}
)

func NewRelation(cli zrpc.Client) Relation {
	return &defaultRelation{
		cli: cli,
	}
}

func (m *defaultRelation) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultRelation) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Unfollow(ctx, in, opts...)
}

func (m *defaultRelation) Status(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Status(ctx, in, opts...)
}

func (m *defaultRelation) ListFollowing(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.ListFollowing(ctx, in, opts...)
}

func (m *defaultRelation) ListFollowers(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.ListFollowers(ctx, in, opts...)
}
