// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowPostsFieldNames          = builder.RawFieldNames(&KnowPosts{})
	knowPostsRows                = strings.Join(knowPostsFieldNames, ",")
	knowPostsRowsExpectAutoSet   = strings.Join(stringx.Remove(knowPostsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowPostsRowsWithPlaceHolder = strings.Join(stringx.Remove(knowPostsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKnowPostsIdPrefix = "cache:knowPosts:id:"
)

type (
	knowPostsModel interface {
		Insert(ctx context.Context, data *KnowPosts) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*KnowPosts, error)
		Update(ctx context.Context, data *KnowPosts) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultKnowPostsModel struct {
		sqlc.CachedConn
		table string
	}

	KnowPosts struct {
		Id               uint64         `db:"id"`
		TagId            sql.NullInt64  `db:"tag_id"` // 主分类/内容分类ID
		Tags             sql.NullString `db:"tags"`   // 标签名数组，例如 ["java","编程"]
		Title            sql.NullString `db:"title"`
		Description      sql.NullString `db:"description"`        // 摘要/描述，最多50字
		ContentUrl       sql.NullString `db:"content_url"`        // 正文存储于OSS的访问URL或签名URL
		ContentObjectKey sql.NullString `db:"content_object_key"` // OSS对象Key
		ContentEtag      sql.NullString `db:"content_etag"`       // OSS ETag（用于校验）
		ContentSize      sql.NullInt64  `db:"content_size"`       // 正文字节大小
		ContentSha256    sql.NullString `db:"content_sha256"`     // 正文SHA-256哈希（hex）
		CreatorId        uint64         `db:"creator_id"`
		IsTop            int64          `db:"is_top"`
		Type             string         `db:"type"`
		Visible          string         `db:"visible"`
		ImgUrls          sql.NullString `db:"img_urls"`  // 图片URL数组或对象数组
		VideoUrl         sql.NullString `db:"video_url"` // 视频URL（一期不使用）
		Status           string         `db:"status"`
		CreateTime       time.Time      `db:"create_time"`
		UpdateTime       time.Time      `db:"update_time"`
		PublishTime      sql.NullTime   `db:"publish_time"`
	}
)

func newKnowPostsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultKnowPostsModel {
	return &defaultKnowPostsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`know_posts`",
	}
}

func (m *defaultKnowPostsModel) Delete(ctx context.Context, id uint64) error {
	knowPostsIdKey := fmt.Sprintf("%s%v", cacheKnowPostsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, knowPostsIdKey)
	return err
}

func (m *defaultKnowPostsModel) FindOne(ctx context.Context, id uint64) (*KnowPosts, error) {
	knowPostsIdKey := fmt.Sprintf("%s%v", cacheKnowPostsIdPrefix, id)
	var resp KnowPosts
	err := m.QueryRowCtx(ctx, &resp, knowPostsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowPostsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowPostsModel) Insert(ctx context.Context, data *KnowPosts) (sql.Result, error) {
	knowPostsIdKey := fmt.Sprintf("%s%v", cacheKnowPostsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, knowPostsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.TagId, data.Tags, data.Title, data.Description, data.ContentUrl, data.ContentObjectKey, data.ContentEtag, data.ContentSize, data.ContentSha256, data.CreatorId, data.IsTop, data.Type, data.Visible, data.ImgUrls, data.VideoUrl, data.Status, data.PublishTime)
	}, knowPostsIdKey)
	return ret, err
}

func (m *defaultKnowPostsModel) Update(ctx context.Context, data *KnowPosts) error {
	knowPostsIdKey := fmt.Sprintf("%s%v", cacheKnowPostsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, knowPostsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TagId, data.Tags, data.Title, data.Description, data.ContentUrl, data.ContentObjectKey, data.ContentEtag, data.ContentSize, data.ContentSha256, data.CreatorId, data.IsTop, data.Type, data.Visible, data.ImgUrls, data.VideoUrl, data.Status, data.PublishTime, data.Id)
	}, knowPostsIdKey)
	return err
}

func (m *defaultKnowPostsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKnowPostsIdPrefix, primary)
}

func (m *defaultKnowPostsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowPostsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultKnowPostsModel) tableName() string {
	return m.table
}
