// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type PresignReq struct {
	Scene       string `json:"scene"` // knowpost_content / knowpost_image
	PostId      string `json:"postId"`
	ContentType string `json:"contentType"`
	Ext         string `json:"ext,optional"`
}

type PresignResp struct {
	Url        string            `json:"url"`
	ObjectKey  string            `json:"objectKey"`
	ExpiresIn  int64             `json:"expiresIn"`
	Headers    map[string]string `json:"headers"`
	ContentUrl string            `json:"contentUrl"`
}
