// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/user/rpc/internal/logic/auth"
	"github.com/zhiguang/zhiguang-go/services/user/rpc/internal/svc"
	"github.com/zhiguang/zhiguang-go/services/user/rpc/user"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) SendCode(ctx context.Context, in *user.SendCodeReq) (*user.SendCodeResp, error) {
	l := authlogic.NewSendCodeLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

func (s *AuthServer) Register(ctx context.Context, in *user.RegisterReq) (*user.AuthResp, error) {
	l := authlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthServer) Login(ctx context.Context, in *user.LoginReq) (*user.AuthResp, error) {
	l := authlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServer) Refresh(ctx context.Context, in *user.RefreshReq) (*user.AuthResp, error) {
	l := authlogic.NewRefreshLogic(ctx, s.svcCtx)
	return l.Refresh(in)
}

func (s *AuthServer) Logout(ctx context.Context, in *user.LogoutReq) (*user.Empty, error) {
	l := authlogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *AuthServer) VerifyToken(ctx context.Context, in *user.VerifyTokenReq) (*user.VerifyTokenResp, error) {
	l := authlogic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}

func (s *AuthServer) PasswordReset(ctx context.Context, in *user.PasswordResetReq) (*user.Empty, error) {
	l := authlogic.NewPasswordResetLogic(ctx, s.svcCtx)
	return l.PasswordReset(in)
}

func (s *AuthServer) RevokeRefresh(ctx context.Context, in *user.RevokeRefreshReq) (*user.RevokeRefreshResp, error) {
	l := authlogic.NewRevokeRefreshLogic(ctx, s.svcCtx)
	return l.RevokeRefresh(in)
}
