// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model_auth

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	loginLogsFieldNames          = builder.RawFieldNames(&LoginLogs{})
	loginLogsRows                = strings.Join(loginLogsFieldNames, ",")
	loginLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(loginLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	loginLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(loginLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLoginLogsIdPrefix = "cache:loginLogs:id:"
)

type (
	loginLogsModel interface {
		Insert(ctx context.Context, data *LoginLogs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*LoginLogs, error)
		Update(ctx context.Context, data *LoginLogs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultLoginLogsModel struct {
		sqlc.CachedConn
		table string
	}

	LoginLogs struct {
		Id         uint64         `db:"id"`
		UserId     sql.NullInt64  `db:"user_id"`
		Identifier string         `db:"identifier"`
		Channel    string         `db:"channel"`
		Ip         sql.NullString `db:"ip"`
		UserAgent  sql.NullString `db:"user_agent"`
		Status     string         `db:"status"`
		CreatedAt  time.Time      `db:"created_at"`
	}
)

func newLoginLogsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLoginLogsModel {
	return &defaultLoginLogsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`login_logs`",
	}
}

func (m *defaultLoginLogsModel) Delete(ctx context.Context, id uint64) error {
	loginLogsIdKey := fmt.Sprintf("%s%v", cacheLoginLogsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, loginLogsIdKey)
	return err
}

func (m *defaultLoginLogsModel) FindOne(ctx context.Context, id uint64) (*LoginLogs, error) {
	loginLogsIdKey := fmt.Sprintf("%s%v", cacheLoginLogsIdPrefix, id)
	var resp LoginLogs
	err := m.QueryRowCtx(ctx, &resp, loginLogsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginLogsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLoginLogsModel) Insert(ctx context.Context, data *LoginLogs) (sql.Result, error) {
	loginLogsIdKey := fmt.Sprintf("%s%v", cacheLoginLogsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, loginLogsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Identifier, data.Channel, data.Ip, data.UserAgent, data.Status)
	}, loginLogsIdKey)
	return ret, err
}

func (m *defaultLoginLogsModel) Update(ctx context.Context, data *LoginLogs) error {
	loginLogsIdKey := fmt.Sprintf("%s%v", cacheLoginLogsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, loginLogsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Identifier, data.Channel, data.Ip, data.UserAgent, data.Status, data.Id)
	}, loginLogsIdKey)
	return err
}

func (m *defaultLoginLogsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLoginLogsIdPrefix, primary)
}

func (m *defaultLoginLogsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginLogsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLoginLogsModel) tableName() string {
	return m.table
}
