// Code generated by goctl. Manually adjusted: 接入 AuthRpcMiddleware（强制鉴权）。

package handler

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest"
	"github.com/zhiguang/zhiguang-go/common/middleware"
	"github.com/zhiguang/zhiguang-go/services/profile/api/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	authMw := middleware.NewAuthRpcMiddleware(serverCtx.AuthRpc, true)
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{authMw.Handle},
			[]rest.Route{
				{Method: http.MethodGet, Path: "/me", Handler: GetMeHandler(serverCtx)},
				{Method: http.MethodPatch, Path: "/", Handler: PatchProfileHandler(serverCtx)},
				{Method: http.MethodPost, Path: "/avatar", Handler: UploadAvatarHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/api/v1/profile"),
	)
}
