// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: counter.proto

package counter

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/counter/rpc/counter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetCountsReq  = counter.BatchGetCountsReq
	BatchGetCountsResp = counter.BatchGetCountsResp
	GetCountsReq       = counter.GetCountsReq
	GetCountsResp      = counter.GetCountsResp
	IsMarkedReq        = counter.IsMarkedReq
	IsMarkedResp       = counter.IsMarkedResp
	ToggleReq          = counter.ToggleReq
	ToggleResp         = counter.ToggleResp

	Counter interface {
		Toggle(ctx context.Context, in *ToggleReq, opts ...grpc.CallOption) (*ToggleResp, error)
		GetCounts(ctx context.Context, in *GetCountsReq, opts ...grpc.CallOption) (*GetCountsResp, error)
		IsMarked(ctx context.Context, in *IsMarkedReq, opts ...grpc.CallOption) (*IsMarkedResp, error)
		BatchGetCounts(ctx context.Context, in *BatchGetCountsReq, opts ...grpc.CallOption) (*BatchGetCountsResp, error)
	}

	defaultCounter struct {
		cli zrpc.Client
	}
)

func NewCounter(cli zrpc.Client) Counter {
	return &defaultCounter{
		cli: cli,
	}
}

func (m *defaultCounter) Toggle(ctx context.Context, in *ToggleReq, opts ...grpc.CallOption) (*ToggleResp, error) {
	client := counter.NewCounterClient(m.cli.Conn())
	return client.Toggle(ctx, in, opts...)
}

func (m *defaultCounter) GetCounts(ctx context.Context, in *GetCountsReq, opts ...grpc.CallOption) (*GetCountsResp, error) {
	client := counter.NewCounterClient(m.cli.Conn())
	return client.GetCounts(ctx, in, opts...)
}

func (m *defaultCounter) IsMarked(ctx context.Context, in *IsMarkedReq, opts ...grpc.CallOption) (*IsMarkedResp, error) {
	client := counter.NewCounterClient(m.cli.Conn())
	return client.IsMarked(ctx, in, opts...)
}

func (m *defaultCounter) BatchGetCounts(ctx context.Context, in *BatchGetCountsReq, opts ...grpc.CallOption) (*BatchGetCountsResp, error) {
	client := counter.NewCounterClient(m.cli.Conn())
	return client.BatchGetCounts(ctx, in, opts...)
}
