// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthResp struct {
	User  AuthUser  `json:"user"`
	Token TokenPair `json:"token"`
}

type AuthUser struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Phone    string `json:"phone"`
	ZgId     string `json:"zgId"`
	ZhId     string `json:"zhId"`
	Birthday string `json:"birthday"`
	School   string `json:"school"`
	Bio      string `json:"bio"`
	Gender   string `json:"gender"`
	TagsJson string `json:"tagsJson"`
	TagJson  string `json:"tagJson"`
	Email    string `json:"email"`
	Skills   []string `json:"skills,optional"`
}

type Empty struct {
}

type LoginReq struct {
	IdentifierType string `json:"identifierType,optional"`
	Identifier     string `json:"identifier"`
	Password       string `json:"password,optional"`
	Code           string `json:"code,optional"`
	Channel        string `json:"channel,optional"` // PASSWORD / CODE（前端可不传）
}

type LogoutReq struct {
	RefreshToken string `json:"refreshToken"`
}

type PasswordResetReq struct {
	Identifier  string `json:"identifier"`
	Code        string `json:"code"`
	NewPassword string `json:"newPassword"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterReq struct {
	IdentifierType string `json:"identifierType,optional"`
	Identifier     string `json:"identifier"`
	Password       string `json:"password"`
	Code           string `json:"code"`
	Nickname       string `json:"nickname,optional"`
	AgreeTerms     bool   `json:"agreeTerms"`
}

type SendCodeReq struct {
	Scene          string `json:"scene"` // REGISTER / LOGIN / RESET_PASSWORD
	IdentifierType string `json:"identifierType,optional"`
	Identifier     string `json:"identifier"`
}

type SendCodeResp struct {
	CooldownSeconds int32 `json:"cooldownSeconds"`
	ExpireSeconds   int32 `json:"expireSeconds"`
}

type TokenPair struct {
	AccessToken           string `json:"accessToken"`
	AccessExpiresAt       int64  `json:"accessExpiresAt"`
	AccessTokenExpiresAt  int64  `json:"accessTokenExpiresAt"`
	RefreshToken          string `json:"refreshToken"`
	RefreshExpiresAt      int64  `json:"refreshExpiresAt"`
	RefreshTokenExpiresAt int64  `json:"refreshTokenExpiresAt"`
	RefreshTokenId        string `json:"refreshTokenId"`
}
