// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/relation/relation.proto

package relation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Follow / Unfollow 写路径：仅写 following 表 + outbox（同事务）；
// follower 反查表、ZSet、usercounter 由 relation-syncer 异步消费 canal-outbox 后落地。
type FollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowReq) Reset() {
	*x = FollowReq{}
	mi := &file_proto_relation_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowReq) ProtoMessage() {}

func (x *FollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowReq.ProtoReflect.Descriptor instead.
func (*FollowReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{0}
}

func (x *FollowReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FollowReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

type FollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResp) Reset() {
	*x = FollowResp{}
	mi := &file_proto_relation_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResp) ProtoMessage() {}

func (x *FollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResp.ProtoReflect.Descriptor instead.
func (*FollowResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResp) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type UnfollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowReq) Reset() {
	*x = UnfollowReq{}
	mi := &file_proto_relation_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowReq) ProtoMessage() {}

func (x *UnfollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowReq.ProtoReflect.Descriptor instead.
func (*UnfollowReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *UnfollowReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

type UnfollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResp) Reset() {
	*x = UnfollowResp{}
	mi := &file_proto_relation_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResp) ProtoMessage() {}

func (x *UnfollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResp.ProtoReflect.Descriptor instead.
func (*UnfollowResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowResp) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

// Status 互查：following/followed_by/mutual 三态。
type StatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	mi := &file_proto_relation_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{4}
}

func (x *StatusReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *StatusReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     bool                   `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	FollowedBy    bool                   `protobuf:"varint,2,opt,name=followed_by,json=followedBy,proto3" json:"followed_by,omitempty"`
	Mutual        bool                   `protobuf:"varint,3,opt,name=mutual,proto3" json:"mutual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_proto_relation_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResp) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

func (x *StatusResp) GetFollowedBy() bool {
	if x != nil {
		return x.FollowedBy
	}
	return false
}

func (x *StatusResp) GetMutual() bool {
	if x != nil {
		return x.Mutual
	}
	return false
}

// 列表分页：offset 优先；offset=0 时启用 cursor（毫秒时间戳，配合 ZSet score 做稳定深分页）。
type ListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 1..100
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Cursor        int64                  `protobuf:"varint,4,opt,name=cursor,proto3" json:"cursor,omitempty"` // 0 表示首页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_proto_relation_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{6}
}

func (x *ListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type UserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ZgId          string                 `protobuf:"bytes,4,opt,name=zg_id,json=zgId,proto3" json:"zg_id,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_proto_relation_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{7}
}

func (x *UserSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserSummary) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserSummary) GetZgId() string {
	if x != nil {
		return x.ZgId
	}
	return ""
}

func (x *UserSummary) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type ListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserSummary         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 0 表示无更多
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_proto_relation_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_relation_proto_rawDescGZIP(), []int{8}
}

func (x *ListResp) GetItems() []*UserSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResp) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *ListResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_proto_relation_relation_proto protoreflect.FileDescriptor

const file_proto_relation_relation_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/relation/relation.proto\x12\brelation\"K\n" +
	"\tFollowReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\"&\n" +
	"\n" +
	"FollowResp\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\"M\n" +
	"\vUnfollowReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\"(\n" +
	"\fUnfollowResp\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\"K\n" +
	"\tStatusReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\"c\n" +
	"\n" +
	"StatusResp\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\x12\x1f\n" +
	"\vfollowed_by\x18\x02 \x01(\bR\n" +
	"followedBy\x12\x16\n" +
	"\x06mutual\x18\x03 \x01(\bR\x06mutual\"h\n" +
	"\aListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\x03R\x06cursor\"x\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x13\n" +
	"\x05zg_id\x18\x04 \x01(\tR\x04zgId\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\"s\n" +
	"\bListResp\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.relation.UserSummaryR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\x9f\x02\n" +
	"\bRelation\x123\n" +
	"\x06Follow\x12\x13.relation.FollowReq\x1a\x14.relation.FollowResp\x129\n" +
	"\bUnfollow\x12\x15.relation.UnfollowReq\x1a\x16.relation.UnfollowResp\x123\n" +
	"\x06Status\x12\x13.relation.StatusReq\x1a\x14.relation.StatusResp\x126\n" +
	"\rListFollowing\x12\x11.relation.ListReq\x1a\x12.relation.ListResp\x126\n" +
	"\rListFollowers\x12\x11.relation.ListReq\x1a\x12.relation.ListRespB\fZ\n" +
	"./relationb\x06proto3"

var (
	file_proto_relation_relation_proto_rawDescOnce sync.Once
	file_proto_relation_relation_proto_rawDescData []byte
)

func file_proto_relation_relation_proto_rawDescGZIP() []byte {
	file_proto_relation_relation_proto_rawDescOnce.Do(func() {
		file_proto_relation_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_relation_relation_proto_rawDesc), len(file_proto_relation_relation_proto_rawDesc)))
	})
	return file_proto_relation_relation_proto_rawDescData
}

var file_proto_relation_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_relation_relation_proto_goTypes = []any{
	(*FollowReq)(nil),    // 0: relation.FollowReq
	(*FollowResp)(nil),   // 1: relation.FollowResp
	(*UnfollowReq)(nil),  // 2: relation.UnfollowReq
	(*UnfollowResp)(nil), // 3: relation.UnfollowResp
	(*StatusReq)(nil),    // 4: relation.StatusReq
	(*StatusResp)(nil),   // 5: relation.StatusResp
	(*ListReq)(nil),      // 6: relation.ListReq
	(*UserSummary)(nil),  // 7: relation.UserSummary
	(*ListResp)(nil),     // 8: relation.ListResp
}
var file_proto_relation_relation_proto_depIdxs = []int32{
	7, // 0: relation.ListResp.items:type_name -> relation.UserSummary
	0, // 1: relation.Relation.Follow:input_type -> relation.FollowReq
	2, // 2: relation.Relation.Unfollow:input_type -> relation.UnfollowReq
	4, // 3: relation.Relation.Status:input_type -> relation.StatusReq
	6, // 4: relation.Relation.ListFollowing:input_type -> relation.ListReq
	6, // 5: relation.Relation.ListFollowers:input_type -> relation.ListReq
	1, // 6: relation.Relation.Follow:output_type -> relation.FollowResp
	3, // 7: relation.Relation.Unfollow:output_type -> relation.UnfollowResp
	5, // 8: relation.Relation.Status:output_type -> relation.StatusResp
	8, // 9: relation.Relation.ListFollowing:output_type -> relation.ListResp
	8, // 10: relation.Relation.ListFollowers:output_type -> relation.ListResp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_relation_relation_proto_init() }
func file_proto_relation_relation_proto_init() {
	if File_proto_relation_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_relation_relation_proto_rawDesc), len(file_proto_relation_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_relation_relation_proto_goTypes,
		DependencyIndexes: file_proto_relation_relation_proto_depIdxs,
		MessageInfos:      file_proto_relation_relation_proto_msgTypes,
	}.Build()
	File_proto_relation_relation_proto = out.File
	file_proto_relation_relation_proto_goTypes = nil
	file_proto_relation_relation_proto_depIdxs = nil
}
