// Code generated by goctl. Manually adjusted: 公开路由可选鉴权 + 鉴权路由强制鉴权。

package handler

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest"
	"github.com/zhiguang/zhiguang-go/common/middleware"
	"github.com/zhiguang/zhiguang-go/services/knowpost/api/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	optMw := middleware.NewAuthRpcMiddleware(serverCtx.AuthRpc, false)
	authMw := middleware.NewAuthRpcMiddleware(serverCtx.AuthRpc, true)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{optMw.Handle},
			[]rest.Route{
				{Method: http.MethodGet, Path: "/feed", Handler: GetPublicFeedHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/detail/:id", Handler: GetDetailPublicHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/:id/qa/stream", Handler: QaStreamCompatHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/api/v1/knowposts"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{authMw.Handle},
			[]rest.Route{
				{Method: http.MethodPost, Path: "/drafts", Handler: CreateDraftHandler(serverCtx)},
				{Method: http.MethodPost, Path: "/:id/content/confirm", Handler: ConfirmContentHandler(serverCtx)},
				{Method: http.MethodPatch, Path: "/:id", Handler: PatchMetadataHandler(serverCtx)},
				{Method: http.MethodPost, Path: "/:id/publish", Handler: PublishHandler(serverCtx)},
				{Method: http.MethodPatch, Path: "/:id/top", Handler: UpdateTopHandler(serverCtx)},
				{Method: http.MethodPatch, Path: "/:id/visibility", Handler: UpdateVisibilityHandler(serverCtx)},
				{Method: http.MethodDelete, Path: "/:id", Handler: DeleteHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/mine", Handler: GetMyFeedHandler(serverCtx)},
				{Method: http.MethodPost, Path: "/:id/reindex", Handler: ReindexHandler(serverCtx)},
				{Method: http.MethodPost, Path: "/:id/rag/reindex", Handler: ReindexHandler(serverCtx)},
				{Method: http.MethodPost, Path: "/description/suggest", Handler: SuggestDescriptionCompatHandler(serverCtx)},
			}...,
		),
		rest.WithPrefix("/api/v1/knowposts"),
	)
}
