// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Tags          string                 `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	After         string                 `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
	ViewerId      int64                  `protobuf:"varint,5,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchReq) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *SearchReq) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *SearchReq) GetViewerId() int64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

type Hit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverImage     string                 `protobuf:"bytes,4,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Tags           []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	TagJson        string                 `protobuf:"bytes,6,opt,name=tag_json,json=tagJson,proto3" json:"tag_json,omitempty"`
	AuthorId       int64                  `protobuf:"varint,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorNickname string                 `protobuf:"bytes,8,opt,name=author_nickname,json=authorNickname,proto3" json:"author_nickname,omitempty"`
	AuthorAvatar   string                 `protobuf:"bytes,9,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"`
	LikeCount      int32                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	FavoriteCount  int32                  `protobuf:"varint,11,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	Liked          bool                   `protobuf:"varint,12,opt,name=liked,proto3" json:"liked,omitempty"`
	Faved          bool                   `protobuf:"varint,13,opt,name=faved,proto3" json:"faved,omitempty"`
	IsTop          bool                   `protobuf:"varint,14,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hit) Reset() {
	*x = Hit{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *Hit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Hit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Hit) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Hit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Hit) GetTagJson() string {
	if x != nil {
		return x.TagJson
	}
	return ""
}

func (x *Hit) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Hit) GetAuthorNickname() string {
	if x != nil {
		return x.AuthorNickname
	}
	return ""
}

func (x *Hit) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

func (x *Hit) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Hit) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Hit) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *Hit) GetFaved() bool {
	if x != nil {
		return x.Faved
	}
	return false
}

func (x *Hit) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Hit                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextAfter     string                 `protobuf:"bytes,2,opt,name=next_after,json=nextAfter,proto3" json:"next_after,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResp) GetItems() []*Hit {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResp) GetNextAfter() string {
	if x != nil {
		return x.NextAfter
	}
	return ""
}

func (x *SearchResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SuggestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestReq) Reset() {
	*x = SuggestReq{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestReq) ProtoMessage() {}

func (x *SuggestReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestReq.ProtoReflect.Descriptor instead.
func (*SuggestReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestReq) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SuggestReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SuggestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestResp) Reset() {
	*x = SuggestResp{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResp) ProtoMessage() {}

func (x *SuggestResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResp.ProtoReflect.Descriptor instead.
func (*SuggestResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestResp) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x06search\"t\n" +
	"\tSearchReq\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04tags\x18\x03 \x01(\tR\x04tags\x12\x14\n" +
	"\x05after\x18\x04 \x01(\tR\x05after\x12\x1b\n" +
	"\tviewer_id\x18\x05 \x01(\x03R\bviewerId\"\x91\x03\n" +
	"\x03Hit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcover_image\x18\x04 \x01(\tR\n" +
	"coverImage\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x19\n" +
	"\btag_json\x18\x06 \x01(\tR\atagJson\x12\x1b\n" +
	"\tauthor_id\x18\a \x01(\x03R\bauthorId\x12'\n" +
	"\x0fauthor_nickname\x18\b \x01(\tR\x0eauthorNickname\x12#\n" +
	"\rauthor_avatar\x18\t \x01(\tR\fauthorAvatar\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x05R\tlikeCount\x12%\n" +
	"\x0efavorite_count\x18\v \x01(\x05R\rfavoriteCount\x12\x14\n" +
	"\x05liked\x18\f \x01(\bR\x05liked\x12\x14\n" +
	"\x05faved\x18\r \x01(\bR\x05faved\x12\x15\n" +
	"\x06is_top\x18\x0e \x01(\bR\x05isTop\"i\n" +
	"\n" +
	"SearchResp\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.search.HitR\x05items\x12\x1d\n" +
	"\n" +
	"next_after\x18\x02 \x01(\tR\tnextAfter\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"8\n" +
	"\n" +
	"SuggestReq\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"#\n" +
	"\vSuggestResp\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items2m\n" +
	"\x06Search\x12/\n" +
	"\x06Search\x12\x11.search.SearchReq\x1a\x12.search.SearchResp\x122\n" +
	"\aSuggest\x12\x12.search.SuggestReq\x1a\x13.search.SuggestRespB\n" +
	"Z\b./searchb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_search_proto_goTypes = []any{
	(*SearchReq)(nil),   // 0: search.SearchReq
	(*Hit)(nil),         // 1: search.Hit
	(*SearchResp)(nil),  // 2: search.SearchResp
	(*SuggestReq)(nil),  // 3: search.SuggestReq
	(*SuggestResp)(nil), // 4: search.SuggestResp
}
var file_search_proto_depIdxs = []int32{
	1, // 0: search.SearchResp.items:type_name -> search.Hit
	0, // 1: search.Search.Search:input_type -> search.SearchReq
	3, // 2: search.Search.Suggest:input_type -> search.SuggestReq
	2, // 3: search.Search.Search:output_type -> search.SearchResp
	4, // 4: search.Search.Suggest:output_type -> search.SuggestResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
