// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: counter.proto

package server

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/counter/rpc/counter"
	"github.com/zhiguang/zhiguang-go/services/counter/rpc/internal/logic/usercounter"
	"github.com/zhiguang/zhiguang-go/services/counter/rpc/internal/svc"
)

type UserCounterServer struct {
	svcCtx *svc.ServiceContext
	counter.UnimplementedUserCounterServer
}

func NewUserCounterServer(svcCtx *svc.ServiceContext) *UserCounterServer {
	return &UserCounterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCounterServer) UserIncrement(ctx context.Context, in *counter.UserIncrementReq) (*counter.UserIncrementResp, error) {
	l := usercounterlogic.NewUserIncrementLogic(ctx, s.svcCtx)
	return l.UserIncrement(in)
}

func (s *UserCounterServer) GetUserSnapshot(ctx context.Context, in *counter.GetUserSnapshotReq) (*counter.GetUserSnapshotResp, error) {
	l := usercounterlogic.NewGetUserSnapshotLogic(ctx, s.svcCtx)
	return l.GetUserSnapshot(in)
}

func (s *UserCounterServer) BatchGetUserSnapshot(ctx context.Context, in *counter.BatchGetUserSnapshotReq) (*counter.BatchGetUserSnapshotResp, error) {
	l := usercounterlogic.NewBatchGetUserSnapshotLogic(ctx, s.svcCtx)
	return l.BatchGetUserSnapshot(in)
}
