// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: llm.proto

package llm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Llm_Describe_FullMethodName = "/llm.Llm/Describe"
	Llm_QaStream_FullMethodName = "/llm.Llm/QaStream"
)

// LlmClient is the client API for Llm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmClient interface {
	Describe(ctx context.Context, in *DescribeReq, opts ...grpc.CallOption) (*DescribeResp, error)
	QaStream(ctx context.Context, in *QaStreamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QaChunk], error)
}

type llmClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmClient(cc grpc.ClientConnInterface) LlmClient {
	return &llmClient{cc}
}

func (c *llmClient) Describe(ctx context.Context, in *DescribeReq, opts ...grpc.CallOption) (*DescribeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResp)
	err := c.cc.Invoke(ctx, Llm_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmClient) QaStream(ctx context.Context, in *QaStreamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QaChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Llm_ServiceDesc.Streams[0], Llm_QaStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QaStreamReq, QaChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Llm_QaStreamClient = grpc.ServerStreamingClient[QaChunk]

// LlmServer is the server API for Llm service.
// All implementations must embed UnimplementedLlmServer
// for forward compatibility.
type LlmServer interface {
	Describe(context.Context, *DescribeReq) (*DescribeResp, error)
	QaStream(*QaStreamReq, grpc.ServerStreamingServer[QaChunk]) error
	mustEmbedUnimplementedLlmServer()
}

// UnimplementedLlmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmServer struct{}

func (UnimplementedLlmServer) Describe(context.Context, *DescribeReq) (*DescribeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedLlmServer) QaStream(*QaStreamReq, grpc.ServerStreamingServer[QaChunk]) error {
	return status.Error(codes.Unimplemented, "method QaStream not implemented")
}
func (UnimplementedLlmServer) mustEmbedUnimplementedLlmServer() {}
func (UnimplementedLlmServer) testEmbeddedByValue()             {}

// UnsafeLlmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmServer will
// result in compilation errors.
type UnsafeLlmServer interface {
	mustEmbedUnimplementedLlmServer()
}

func RegisterLlmServer(s grpc.ServiceRegistrar, srv LlmServer) {
	// If the following call panics, it indicates UnimplementedLlmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Llm_ServiceDesc, srv)
}

func _Llm_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Llm_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServer).Describe(ctx, req.(*DescribeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Llm_QaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QaStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LlmServer).QaStream(m, &grpc.GenericServerStream[QaStreamReq, QaChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Llm_QaStreamServer = grpc.ServerStreamingServer[QaChunk]

// Llm_ServiceDesc is the grpc.ServiceDesc for Llm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Llm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.Llm",
	HandlerType: (*LlmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Llm_Describe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QaStream",
			Handler:       _Llm_QaStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "llm.proto",
}
