// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: knowpost.proto

package server

import (
	"context"

	"github.com/zhiguang/zhiguang-go/services/knowpost/rpc/internal/logic/knowpost"
	"github.com/zhiguang/zhiguang-go/services/knowpost/rpc/internal/svc"
	"github.com/zhiguang/zhiguang-go/services/knowpost/rpc/knowpost"
)

type KnowPostServer struct {
	svcCtx *svc.ServiceContext
	knowpost.UnimplementedKnowPostServer
}

func NewKnowPostServer(svcCtx *svc.ServiceContext) *KnowPostServer {
	return &KnowPostServer{
		svcCtx: svcCtx,
	}
}

func (s *KnowPostServer) CreateDraft(ctx context.Context, in *knowpost.CreateDraftReq) (*knowpost.CreateDraftResp, error) {
	l := knowpostlogic.NewCreateDraftLogic(ctx, s.svcCtx)
	return l.CreateDraft(in)
}

func (s *KnowPostServer) ConfirmContent(ctx context.Context, in *knowpost.ConfirmContentReq) (*knowpost.Empty, error) {
	l := knowpostlogic.NewConfirmContentLogic(ctx, s.svcCtx)
	return l.ConfirmContent(in)
}

func (s *KnowPostServer) PatchMetadata(ctx context.Context, in *knowpost.PatchMetadataReq) (*knowpost.KnowPostDetail, error) {
	l := knowpostlogic.NewPatchMetadataLogic(ctx, s.svcCtx)
	return l.PatchMetadata(in)
}

func (s *KnowPostServer) Publish(ctx context.Context, in *knowpost.PublishReq) (*knowpost.KnowPostDetail, error) {
	l := knowpostlogic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *KnowPostServer) UpdateTop(ctx context.Context, in *knowpost.UpdateTopReq) (*knowpost.Empty, error) {
	l := knowpostlogic.NewUpdateTopLogic(ctx, s.svcCtx)
	return l.UpdateTop(in)
}

func (s *KnowPostServer) UpdateVisibility(ctx context.Context, in *knowpost.UpdateVisibilityReq) (*knowpost.Empty, error) {
	l := knowpostlogic.NewUpdateVisibilityLogic(ctx, s.svcCtx)
	return l.UpdateVisibility(in)
}

func (s *KnowPostServer) Delete(ctx context.Context, in *knowpost.DeleteReq) (*knowpost.Empty, error) {
	l := knowpostlogic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *KnowPostServer) GetDetail(ctx context.Context, in *knowpost.GetDetailReq) (*knowpost.KnowPostDetail, error) {
	l := knowpostlogic.NewGetDetailLogic(ctx, s.svcCtx)
	return l.GetDetail(in)
}

func (s *KnowPostServer) GetPublicFeed(ctx context.Context, in *knowpost.GetPublicFeedReq) (*knowpost.FeedPage, error) {
	l := knowpostlogic.NewGetPublicFeedLogic(ctx, s.svcCtx)
	return l.GetPublicFeed(in)
}

func (s *KnowPostServer) GetMyFeed(ctx context.Context, in *knowpost.GetMyFeedReq) (*knowpost.FeedPage, error) {
	l := knowpostlogic.NewGetMyFeedLogic(ctx, s.svcCtx)
	return l.GetMyFeed(in)
}

func (s *KnowPostServer) Reindex(ctx context.Context, in *knowpost.ReindexReq) (*knowpost.Empty, error) {
	l := knowpostlogic.NewReindexLogic(ctx, s.svcCtx)
	return l.Reindex(in)
}
