// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ActionReq struct {
	EntityType string `json:"entityType"`
	EntityId   string `json:"entityId"`
}

type ActionResp struct {
	Changed bool `json:"changed"`
	Liked   bool `json:"liked,optional"`
	Faved   bool `json:"faved,optional"`
}

type CountsResp struct {
	EntityType string           `json:"entityType"`
	EntityId   string           `json:"entityId"`
	Counts     map[string]int64 `json:"counts"`
}

type GetCountsPath struct {
	EntityType string `path:"etype"`
	EntityId   string `path:"eid"`
}
